### ISSUE TITLE
Laravel 5.4 Compatibilidade

### ISSUE THREAD

**Issue by carlosfiori** [michaeldouglas/laravel-pagseguro#101]
Utilizando o Laravel 5.4 está acontecendo varios erros ao receber a notificação do pagseguro.
De inicio ele informa que a classe Input não foi encontrada, para resolver isso adicionei a classe no meu alias em config/app.php ('Input' => Illuminate\Support\Facades\Input::class).

Após isso o seguinte erro está ocorrendo:
Class 'laravel\pagseguro\Facades\PagSeguroFacade' not found

**Comment by egisberto** [comment]
Mesmo problema @carlosfiori !!! Creio que o bundle não esteja 100% compatível com a versão 5.4 do laravel. Uma pena.

**Comment by egisberto** [comment]
Descobri a treta!!! Tem que adicionar a url da notificação na lista de exceções de verificação do token CSRF!

protected $except = ['pagseguro/*',];
