### ISSUE TITLE
Pagamento Recorrente

### ISSUE THREAD

**Issue by fredroo** [michaeldouglas/laravel-pagseguro#103]
Gostaria de um exemplo para pagamento recorrente

**Comment by fredroo** [comment]
@michaeldouglas pode me ajudar?

**Comment by michaeldouglas** [comment]
@fredroo Estamos trabalhando para liberar o pagamento recorrente na biblioteca.

**Comment by fredroo** [comment]
obrigado pelo retorno, tem previsão?

**Comment by fredroo** [comment]
@michaeldouglas https://github.com/pagseguro/pagseguro-php-sdk/issues/39

**Comment by fredroo** [comment]
@michaeldouglas não tem como se basear no sdk php para implementar o pagamento recorrente?

**Comment by fredroo** [comment]
@michaeldouglas https://github.com/PHPSC/pagseguro essa biblioteca pode te ajudar na questão das assinaturas confere os fontes dela

**Comment by marabesi** [comment]
@fredroo não tem previsão, vou adicionar esse item como enhancement para a próxima versão

**Comment by fredroo** [comment]
blz obrigado @marabesi

**Comment by MarcusMann** [comment]
Bom dia,
Já foi adicionado essa feature ao projeto?

**Comment by fredroo** [comment]
@MarcusMann https://github.com/artistas/laravel-pagseguro
nesse já tem
olha a documentação dele, tem o manual completo

**Comment by MarcusMann** [comment]
Obrigado @fredroo
