### ISSUE TITLE
Problema com a classe InformationFactory

### ISSUE THREAD

**Issue by leandrobastos** [michaeldouglas/laravel-pagseguro#105]
Estou tendo um problema ao tentar converter os dados de retorno de notificação de confirmação de pagamento.
Fiz um debug e o problema está ocorrendo na seguinte função:

public function getSender()
    {
        $data = $this->getSenderDataNormalized();
        $sender = new Sender($data);
        return $sender;
    }

Alguém já possou por esse problema? Como resolver?

Abraço!

**Comment by rafaellupo** [comment]
O último commit quebrou tudo... Não sei se seu problema está relacionado, mas as minhas notificações / transações pararam todas... Agora é sentar e descobrir. Quando eu resolver eu posto o que funcionou pra mim, pode ser que seja o mesmo pra vc.

**Comment by michaeldouglas** [comment]
Irei realizar o retornar a Laravel PagSeguro para o commit anterior.
