### ISSUE TITLE
Erro no checkout

### ISSUE THREAD

**Issue by lsgoulart** [michaeldouglas/laravel-pagseguro#106]
Opa, tenho uma loja em fase de testes e tudo funcionava perfeitamente até ontem, quando rodei um composer update no projeto. A partir disso sempre recebo um erro ao enviar uma tentativa de checkout.

Tentando debugar o que está acontecendo percebi que o `$response = $request->post($url, $credentialData)` está voltando como `false`. Como esse chekout é feito via ajax eu consigo enviar uma segunda tentativa, com os exatos mesmo dados da primeira tentativa e o checkout acontece normalmente.

Alguma dica do que pode estar acontecendo?

Valeu

**Comment by claudiusnascimento** [comment]
Comigo aconteceu a mesma coisa. Estava tudo certo, derepente parou. Estou tentando enviar o código de exemplo que está aqui no repo e da problema na classe CurlAdapter, no método processRequest(); 

A linha:
$body = curl_exec($resource);

$body sempre retorna false, então da erro no checkout.

Alguma ajuda?
Falow.

**Comment by lsgoulart** [comment]
@claudiusnascimento está usando o ambiente de sandbox?

Em produção, aparentemente, está funcionando.

**Comment by claudiusnascimento** [comment]
@lsgoulart, sim, em produção está ok.

As vezes no ambiente de sandbox funciona, mas a maioria das vezes não.

Continuar tentando. Qualquer coisa que descobrir porto aqui.

**Comment by hiroaka** [comment]
Passando por esse problema aqui também, muito estranho

**Comment by claudiusnascimento** [comment]
Com certeza é problema no Sandbox do Pagseguro, porque eu imprimo no browser o xml do checkout, vou até a página de Api do pagseguro, colo o código lá e faço uma requisição e da tudo certo.
Façam login no sandbox e vejam no debug lá que chega a requisição também. Tudo certo...

Acho que o problema está na resposta deles.

**Comment by claudiusnascimento** [comment]
Triste lidar com o PagSeguro.

https://comunidade.pagseguro.uol.com.br/hc/pt-br/community/posts/115000283114-Sandbox-consegue-ser-pior-do-que-um-cavalo-tentando-andar-de-moto?page=1#community_comment_115000712413

https://comunidade.pagseguro.uol.com.br/hc/pt-br/community/posts/115006018047-ERRO-500-Consulta-de-Transa%C3%A7%C3%B5es-por-C%C3%B3digo-de-Refer%C3%AAncia?input_string=Sandbox%20inst%C3%A1vel

**Comment by marabesi** [comment]
Aparentemente é erro do pagseguro, vou fechar a issue se o problema continuar é só abri-la novamente

**Comment by hiroaka** [comment]
@marabesi Olá tudo bem?
Na verdade eu encontrei o motivo disto acontecer, o WS de homologação do Pagseguro esta com uma demora excessiva para responder ao request, o que tive que fazer foi fazer um hardcode na classe para forçar um timeout maior. 
O ideal seria poder aumentar esta função por uma config e atualização essa library para ficar mais bonitinho
