### ISSUE TITLE
Criar drivers para componentes internos do pacote

### ISSUE THREAD

**Issue by xshifty** [michaeldouglas/laravel-pagseguro#11]
Inicialmente, precisamos criar uma interface para drivers do client http.
A idéia é fazer com que o programador consiga usar outros packages para executar requisições http.
Posteriormente, podemos implementar os drivers para outros componentes como o Validation.

**Comment by isaquesb** [comment]
Reabrindo para colocar no milestone 1.5

**Comment by isaquesb** [comment]
Resolvido.
Pode-se substituir o driver de Http implementando a interface.
