### ISSUE TITLE
Error on send: 401-Unauthorized

### ISSUE THREAD

**Issue by pcesarteixeira** [michaeldouglas/laravel-pagseguro#115]
Estou com problemas ao utilizar o Sandbox.
Está retornando o seguinte erro:
`Error on send: 401-Unauthorized`
Quando desativo o sandbox funciona normalmente.

OBS:
Está da seguinte forma no arquivo de configuração:
`'use-sandbox' => true,`

**Comment by michelmelo** [comment]
@pcesarteixeira os dados de acesso a SandBox é diferente de Produção. (até onde sei não da pra usar os mesmos dados.)

**Comment by pcesarteixeira** [comment]
Realmente, acabei dando essa bobeira aqui, perdão pelo vacilo.
