### ISSUE TITLE
cobrança recorrente

### ISSUE THREAD

**Issue by Deboracgs** [michaeldouglas/laravel-pagseguro#129]
como fazer a cobrança recorrente?

**Comment by fredroo** [comment]
@michaeldouglas funciona com cobrança recorrente (assinatura)?

**Comment by fredroo** [comment]
@Deboracgs já conseguiu usar com cobrança recorrente?

**Comment by michaeldouglas** [comment]
@Deboracgs @fredroo 

Estou subindo um deploy agora para a criação dos pagamentos recorrentes.

**Comment by Deboracgs** [comment]
@michaeldouglas faz tempo que vi isto, não me lembro se dei sequência com o laravel.
