### ISSUE TITLE
Inserir o código no ARRAY Providers > Erro no PHP Artisan

### ISSUE THREAD

**Issue by andrehol** [michaeldouglas/laravel-pagseguro#13]
Quando coloco o código no array providers,  o php artisan deixa de funcionar. Dando o seguinte erro:

                                      
  [BadMethodCallException]            
  Call to undefined method [package]  

Sugestões?

**Comment by michaeldouglas** [comment]
Qual código que você esta colocando no providers que está gerando esse erro ?

**Comment by leonardosapiras** [comment]
O mesmo erro acontece para mim. Coloquei o seguinte código no array providers:

laravel\pagseguro\PagseguroServiceProvider::class

E o seguinte código no array aliases:

'PagSeguro' => laravel\pagseguro\Facades\PagSeguro::class

**Comment by leonardosapiras** [comment]
Acho que achei o que causou o problema. Quando eu instalei essa lib, eu o fiz com o composer require michael/laravelpagseguro. Isso baixou a versão 0.4.0. 

Configurei meu composer.json para "michael/laravelpagseguro": "dev-master", rodei o composer update e depois o  php artisan vendor:publish.

Funcionou!

**Comment by andrehol** [comment]
Opa vou tentar esse procedimento. Acho que usei também o composer require.

**Comment by andrehol** [comment]
Exatamente.. o erro desapareceu.. e posso usar o artisan novamente. VALEU.. 
lembrando que devemos usar "use laravel\pagseguro\Facades\PagSeguro; " no cabeçalho do controller.

**Comment by michaeldouglas** [comment]
Galera,

Irei fechar essa issue pois acredito que está tudo correto.

Aproveitando para avisar que existe um novo release do Laravel PagSeguro, esse release contempla o ajuste do erro de dados do comprador onde não estavam chegando corretamente para o PagSeguro.
