### ISSUE TITLE
Método inexistente

### ISSUE THREAD

**Issue by vitordesousa** [michaeldouglas/laravel-pagseguro#130]
Olá!

Estou tentando fazer testes com a package, mas infelizmente não estou conseguindo.
Já nos testes do exemplo informado na documentação, já dá erro.

Segue o mesmo:
`"Call to undefined method laravel\pagseguro\Platform\Laravel5\ServiceProvider::checkout()"`.
![screenshot_22](https://user-images.githubusercontent.com/10253164/38218771-48505156-36a9-11e8-861b-f635e9f68e0e.jpg)

Já chequei e todos os arquivos estão lá. Mas fui neste arquivo em questão, e realmente o método não existe lá. 

Esse é o código que estou utilizando e obtendo o erro:
` $checkout = \PagSeguro::checkout()->createFromArray($data);`
`dd($checkout);`

A variável `$data` é a mesma do exemplo.

Nenhuma das opções da doc funciona e também uma que eu criei também está desse jeito..

Versão do Laravel: `5.5.40`
Versão do PHP: `7.0.25`

PS 1: Já removi a `\` do Pagseguro e continua assim.

Desde já agradeço a ajuda!

**Comment by TopFuel** [comment]
Isso acontece porquê a um erro na implantação do Auto Discovery, já mandei um pull request pra corrigir mas ainda não foi aceito, aqui o link para o pull request: #127 

O jeito mais fácil para corrigir o problema é desativar o Auto Discovery para o pacote e implementar como era no Laravel 5.4, para desativar o Auto Discovery adicione `"michael/laravelpagseguro"` em `"dont-discover"` no composer.json, aqui um link para a documentação do Laravel sobre o Auto Discovery: [https://laravel.com/docs/5.5/packages#package-discovery](https://laravel.com/docs/5.5/packages#package-discovery).

**Comment by michaeldouglas** [comment]
Merge aceito, por favor, teste agora se está correto.
