### ISSUE TITLE
Erro 419 nas notificações

### ISSUE THREAD

**Issue by lapis2006** [michaeldouglas/laravel-pagseguro#131]
Olá!

Eu estou tentando enviar notificações pelo PagSeguro ao sistema que estou criando e não estou conseguindo.  Estou recebendo erro 419 nas notificações.

Estou no Sandbox e enviando através da página de transações. 

O normal é o /notification, mas já alterei a URL várias vezes e não muda o codigo.
Já criei uma outra função para esta URL apenas com um `dd(1)` , e mesmo assim continuo recebendo o código 419.

Segue o print da tela de notificação de transações do Sandbox do Pagseguro:
![screenshot_23](https://user-images.githubusercontent.com/1848864/38572958-0a30b5f0-3ccb-11e8-9400-e79eb13ef43e.jpg)

Obs: A URL está como POST no `web.php`.

**Comment by lapis2006** [comment]
Estava usando a versão 5.5 do Laravel, fiz a atualização para a versão mais recente 5.6+, mas mesmo assim continuo recebendo essa notificação `419`.

Acredito que eu deveria receber `200`, certo?

**Comment by isaquesb** [comment]
@lapis2006 , você já verificou se esta rota esta protegida por csrf?
A rota tem que estar liberada. Se estiver sobre o middleware de csrf ela possivelmente vai retornar esse código 419 quando pagseguro postar a notificação.

**Comment by lapis2006** [comment]
Oi @isaquesb .. verifiquei sim. está sem nada. é início do projeto, ainda não fiz login e senha.

![image](https://user-images.githubusercontent.com/1848864/39012877-1316bb60-43ec-11e8-8866-df67b5e4a14b.png)

No caso o usuário está sendo criado com esse cadastro. E este pagamento neste caso é uma doação.

**Comment by isaquesb** [comment]
@lapis2006 ,

Só para testar, comenta a linha que marca:

\App\Http\Middleware\VerifyCsrfToken::class,

em

app/Http/Kernel.php

É o middleware de csrf aplicado ao middleware "web"

**Comment by lapis2006** [comment]
é.. agora deu 200.

Só não sei agora como solucionar. Pode me dar uma ajuda?

**Comment by lapis2006** [comment]
Ufa! 
Acredito que consegui resolver....
No arquivo `VerifyCsrfToken.php` eu coloquei o `/notification` no `protected $except = [ ];`.

@isaquesb , muito obrigado pela ajuda!
