### ISSUE TITLE
SANDBOX

### ISSUE THREAD

**Issue by ArthurCalazans** [michaeldouglas/laravel-pagseguro#134]
Olá, tudo bem?

Estou utilizando o sua biblioteca de pagseguro e estou com problema em utilizar o sandbox, pois no sandbox.pagseguro.com ele me fornece um token pro vendedor, um token para aplicação, um email do vendedor e o meu e-mail da conta. Não sei qual utilizar.

Poderia me explicar como faço para fazer funcionar o sandbox?

Obrigado!

**Comment by arthurcvm** [comment]
Utiliza as credenciais de vendedor.
