### ISSUE TITLE
Por favor: O facades não deveria ter as funções declararas como static?

### ISSUE THREAD

**Issue by gabrielmoura** [michaeldouglas/laravel-pagseguro#136]

**Comment by crossworth** [comment]
Realmente os facades definidos no código parecem estarem diferentes do que normalmente encontramos em outras bibliotecas Laravel, acredito que o motivo disso seja para tornar o código mais framework-agnostic (o que não entendi muito bem o motivo já que o nome é laravel-pagseguro), de qualquer forma tu pode instanciar o objeto e usar normalmente (nesse caso tu teria que definir a plataforma como Laravel5, pelo menos para Laravel 5.6) ou pode usar o `Aliases` definido no `app.php`
