### ISSUE TITLE
"Undefined platform router"

### ISSUE THREAD

**Issue by gabrielmoura** [michaeldouglas/laravel-pagseguro#137]
No arquivo laravel/pagseguro/Remote/Url/Resolver.php
nas linhas 105 -120.
Apresenta esse erro com o laravel 5.6, php7.2

**Comment by crossworth** [comment]
Utilize o `Aliases` definido de no `app.php`

```
use PagSeguro;
```

Ou utilize o facade direto `laravel\pagseguro\Platform\Laravel5\PagSeguro`.
