### ISSUE TITLE
Assinaturas

### ISSUE THREAD

**Issue by leonardosapiras** [michaeldouglas/laravel-pagseguro#14]
Essa lib permite realizar assinaturas? Se sim, existem algum exemplo?

**Comment by marabesi** [comment]
Quais tipos de assinatura @leonardosapiras ?

**Comment by isaquesb** [comment]
A intenção é colocar assinaturas também. Vou criar uns milestones assim que possível, para colocar todos os objetivos.

**Comment by marabesi** [comment]
@isaquesb quais tipos de assinaturas são necessárias ? Tem como descreve-las ?

**Comment by marabesi** [comment]
https://pagseguro.uol.com.br/para_seu_negocio/assinaturas.jhtml#rmcl

**Comment by deyvisonrocha** [comment]
Alguma novidade pessoal?

**Comment by rickygomez** [comment]
Também gostaria de saber se essa lib tem esse recurso e como posso usar. 
Estou desenvolvendo um sistema que vai necessitara de uma cobrança mensal pré-aprovada.

**Comment by spaceonline** [comment]
+1

**Comment by marabesi** [comment]
Galera, ontem @michaeldouglas  e eu estivemos no forum ecommerce e falamos com o pessoal do UOL. Provavelmente iremos implementar isso em breve, pra isso iremos utilizar a v3 e não mais a v2.

Assim que tivermos mais novidades informo vocês

**Comment by codzero** [comment]
Opa pessoal, isso aqui ta ficando lindo, alguma novidade sobre a assinatura ?

**Comment by charleskx** [comment]
Alguma novidade quanto ao recurso de assinaturas?

**Comment by lhcgoncalves** [comment]
Novidades?

**Comment by robsoncombr** [comment]
+1 assinaturas
