### ISSUE TITLE
Compatibilidade para Checkout Transparente com o Laravel Cashier (5.8)

### ISSUE THREAD

**Issue by timoteo7** [michaeldouglas/laravel-pagseguro#142]
Olá,

 a biblioteca é compativel com o [Laravel Cashier](https://laravel.com/docs/5.8/billing) (5.8)

para um Checkout Transparente ?

**Comment by fredroo** [comment]
@michaeldouglas também gostaria de saber

**Comment by braulioholtz** [comment]
Eu acredito que o Laravel Cashier é para implementações com o Stripe.

**Comment by fredroo** [comment]
@braulioholtz não, ele é implementado com Stripe mas pode ser implementado com outros gateways de pagamento

no caso é só ler a documentação e criar para o paypal, pagseguro ou mercado pago por exemplo quem quiser

**Comment by fredroo** [comment]
@timoteo7 acho que seria melhor criar outro projeto que implemente, pode até usar esse projeto aqui e apenas implementar o que precisar para que ele (NOVO PROJETO) seja compatível com Laravel Cashier

seria bom fazer uns teste agora que o @michaeldouglas disse que subiu atualizações 
#129  para que se possa usar assinatura nesse projeto aqui

**Comment by fredroo** [comment]
Aqui tem exemplos com outros gateways de pagamentos

[(https://github.com/laravel/cashier-braintree]
[(https://github.com/laravel/cashier-mollie))]
