### ISSUE TITLE
Erro de parâmetro nullo na class Phone

### ISSUE THREAD

**Issue by meirinaldojunior** [michaeldouglas/laravel-pagseguro#143]
Olá,

Estou me deparando com a seguinte exception na consulta de transações:

```Argument 1 passed to laravel\pagseguro\Phone\Phone::__construct() must be of the type array, null given, called in /var/www/html/sys/vendor/michael/laravelpagseguro/src/laravel/pagseguro/Sender/Sender.php on line 145```

A documentação do SDK do pagseguro é precária e omite dizer se terei efeitos colaterais se  não passar este dado no construct.

Alguém que conhece o SDK a fundo para dar um help?

**Comment by meirinaldojunior** [comment]
Resolvi fazendo um fork e comentei o parse do phone temporariamente até encontrar uma solução ideal... 

Obrigado pela dica.

**Comment by aquinopro** [comment]
Estou com o mesmo problema aqui quando recebo notificações do pagseguro.

Symfony\Component\Debug\Exception\FatalThrowableError
Argument 1 passed to laravel\pagseguro\Phone\Phone::__construct() must be of the type array, null given, called in /vendor/michael/laravelpagseguro/src/laravel/pagseguro/Sender/Sender.php on line 145
