### ISSUE TITLE
Compra sem telefone informado

### ISSUE THREAD

**Issue by Dserma** [michaeldouglas/laravel-pagseguro#151]
Bom dia.
Acabei de passar por uma situação um tanto quanto inusitada.
O retorno do PagSeguro estava acusando erro 500 em minha aplicação, e ao verificar constatei que o erro estava na classe Phone, pois o mesmo espera um array, e null estava sendo passado. 
Depois de debugar, cheguei à raiz do problema: não sei como, mas o cliente conseguiu realizar a compra, via lightbox, sem informar o telefone, então esse dado não vinha no retorno do PagSeguro, o que ocasionava o erro.
Contornei isso colocando um if, na função setPhone da classe Sender, que verifica se a variável $phone é vazia ou não, e sendo vazia, eu pego o telefone do usuário através de um repositório meu, passando o e-mail como chave.
Seria interessante fazer essa verificação por default, e quando for vazio, apenas retorna o $this->phone como null mesmo.

Abs.

**Comment by michaeldouglas** [comment]
@Dserma tivemos um pull request que ajustou esse questão:

https://github.com/michaeldouglas/laravel-pagseguro/commit/98bfa8208541319535b199ed9a0cce9daee345a4
