### ISSUE TITLE
Melhoria no pagseguro config

### ISSUE THREAD

**Issue by andrehol** [michaeldouglas/laravel-pagseguro#16]
Acrescentei em meu projeto uma melhoria na configuração do pagseguro  

"/config/laravelpagseguro.php"

/*
 * Set your enviroment sandbox or production
 * */
$env = 'sandbox'; //production

if ($env == "sandbox"){
    $token = 'seu_token_sandbox';
    $url = 'https://ws.sandbox.pagseguro.uol.com.br';
}
else {
    $token = 'seu_token_de_producao';
    $url = 'https://ws.pagseguro.uol.com.br';
}

return [
    'sandbox' => true,//DEFINI SE SERÁ UTILIZADO O AMBIENTE DE TESTES
    
    'credentials' => [//SETA AS CREDENCIAIS DE SUA LOJA
        'email' => 'teu_email',
        'token' => $token,
    ],
    'currency' => [//MOEDA QUE SERÁ UTILIZADA COMO MEIO DE PAGAMENTO
        'type' => 'BRL'
    ],
    'reference' => [//CRIAR UMA REFERENCIA PARA OS PRODUTOS VENDIDOS
        'idReference' => null
    ],
    'url' => $url,
];

**Comment by isaquesb** [comment]
Reabrindo - Sendo adicionado no milestone. (obs.: trabalhando na branch notification)

**Comment by ricardobarantini** [comment]
Seria legal se essas variáveis ficassem no .env, eu fiz uma modificação assim aqui, meu config do Pagseguro pega as variáveis no .env, ai toda alteração que preciso fazer no servidor só acabo fazendo nesse arquivo.

**Comment by marabesi** [comment]
Por favor, se atentar ao pull request #32 ao realizar essa melhoria para atender também a esse problema

**Comment by isaquesb** [comment]
Sendo trabalhado na branch notification.

**Comment by isaquesb** [comment]
Config melhorado. Pode-se substituir os valores com uso dos envs.
