### ISSUE TITLE
Checkout send failure

### ISSUE THREAD

**Issue by renatotamanaha** [michaeldouglas/laravel-pagseguro#162]
Não consigo saber qual o erro e porque.
Configurei como pedido nas instruções, estou utilizando as informações de $data para testar caso alguma informação que passasse estivesse implicando em erro, mas da o mesmo erro em ambas.
Chequei as credenciais e estão corretas.

Estou usando laravel 7.

**Comment by Emanueltotem** [comment]
Também estou passando pelo mesmo problema, só que estou utilizando a versão 6.

**Comment by michaeldouglas** [comment]
Olá pessoal, veja se agora solucionou.

**Comment by michaeldouglas** [comment]
O problema estava relacionado a um pull request.

**Comment by Emanueltotem** [comment]
Ok, obrigado pela atenção!

**Comment by Emanueltotem** [comment]
Ainda estou passando pelo mesmo problema. Depois que falou que foi solucionado eu atualizei o pacote, mas o problema permaneceu.

**Comment by michaeldouglas** [comment]
@Emanueltotem qual o erro que você está recebendo? - Manda o erro aqui que consigo ajudar você.

**Comment by Emanueltotem** [comment]
Aí está o erro

![Sem título](https://user-images.githubusercontent.com/16547271/91713373-09ade300-eb60-11ea-99d6-0c78d7e4861d.png)

**Comment by michaeldouglas** [comment]
@Emanueltotem Pega a versão exata do seu Laravel 6 para eu reproduzir e verificar se tem alguma coisa, por que fiz em um Laravel 6 aqui e foi, pode ser alguma versão que possa estar causando o erro.

**Comment by Emanueltotem** [comment]
Estou usando a versão 6.18.37

**Comment by michaeldouglas** [comment]
@Emanueltotem Oi Emanuel. Eu fiz um projeto com a mesma versão: https://github.com/michaeldouglas/laravelpagseguro_exemplo_laravel_6 E deixei tudo funcionando e configurado. 

Depois que você subir o projeto basta chamar a rota: http://localhost:8000/pagseguro/pay

Você vai conseguir criar o pagamento, caso isso não aconteça o provavel é que algum dado que está sendo enviado para o checkout esteja errado, tente da maneira que está nesse repo para ver se vai dar certo, abraços.

**Comment by Emanueltotem** [comment]
Obrigado, abraços.

**Comment by alancarlosml** [comment]
Boa noite, estou encontrando um erro semelhante.

Versão do Laravel: 8.50.0.

Estou usando as credenciais fornecidas na página do pagseguro sandbox.

`Error on send: 400-<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>11007</code><message>redirectURL invalid value: http://127.0.0.1:8000/obrigado</message></error><error><code>10044</code><message>Invalid value for notification URL : http://127.0.0.1:8000/notificacoes</message></error></errors>`

Poderiam me dar uma ajuda?
