### ISSUE TITLE
Problemas no callback de notification

### ISSUE THREAD

**Issue by RGusse** [michaeldouglas/laravel-pagseguro#167]
Estou tendo problemas no callback das notifications, configurei meu callback conforme link
https://github.com/michaeldouglas/laravel-pagseguro#recebendo-notifica%C3%A7%C3%B5es-de-transa%C3%A7%C3%A3o
mas ao receber o callback do pagseguro, está retornando "Error on getStatus: 401-Unauthorized".

Alguém saberia como resolver este problema?

**Comment by RGusse** [comment]
mesmo setando o 'use-sandbox' como true no arquivo "laravelpagseguro.php", no arquivo "\remote\url\resolver" o Config::get('use-sandbox') sempre traz false.

**Comment by seomidia** [comment]
@RGusse conseguiu achar uma solução pro problema?

**Comment by RGusse** [comment]
@seomidia o problema só ocorre qdo sandbox, para funcionar eu setei hardcoded o useSandbox como true, no Resolver.

**Comment by thiivalente** [comment]
> @seomidia o problema só ocorre qdo sandbox, para funcionar eu setei hardcoded o useSandbox como true, no Resolver.

Isso resolveu o meu problema, muito obrigado, caso ninguém faça fix até eu ter um tempinho, eu tento ver como corrigir isso oficialmente para subir esse hotfix.

**Comment by WolflanFreitas** [comment]
Funcionou perfeitamente!

**Comment by seomidia** [comment]
Desculpe nao responder, hardcode deu certo
