### ISSUE TITLE
Atualização de Métodos de Pagement ( PIX )

### ISSUE THREAD

**Issue by FormigTeen** [michaeldouglas/laravel-pagseguro#168]
![image](https://user-images.githubusercontent.com/18594451/113416482-d3f00780-9397-11eb-97b2-c2c2124070e9.png)

A Biblioteca não está aceitando pedidos pagos com o PIX, é necessário uma atualização.

**Comment by fredroo** [comment]
https://github.com/pagseguro/pagseguro-sdk-php/issues/218

**Comment by emersonrodrigod** [comment]
Estou usando essa PR, será que tem previsão para mergear?

#173
