### ISSUE TITLE
Erro de "Checkout send failure"

### ISSUE THREAD

**Issue by jouglasw** [michaeldouglas/laravel-pagseguro#171]
Bom dia.
Desde ontem estou tendo problemas na criação de pagamentos no sistema pois está retornando o erro "Checkout send failure". Alguém mais com esse problema? Sabem se a API está operando normalmente? Houve alguma mudança na estrutura?
Parte da resposta da requisição:

"message": "Checkout send failure",
"exception": "RuntimeException",
"file": ".../vendor/michael/laravelpagseguro/src/laravel/pagseguro/Remote/Checkout.php",
"line": 39,
"trace": [
{
"file": ".../vendor/michael/laravelpagseguro/src/laravel/pagseguro/Checkout/SimpleCheckout.php",
"line": 159,
"function": "send",
"class": "laravel\pagseguro\Remote\Checkout",
"type": "->"
},

**Comment by jairdeon** [comment]
> Bom dia. Desde ontem estou tendo problemas na criação de pagamentos no sistema pois está retornando o erro "Checkout send failure". Alguém mais com esse problema? Sabem se a API está operando normalmente? Houve alguma mudança na estrutura? Parte da resposta da requisição:
> 
> "message": "Checkout send failure", "exception": "RuntimeException", "file": ".../vendor/michael/laravelpagseguro/src/laravel/pagseguro/Remote/Checkout.php", "line": 39, "trace": [ { "file": ".../vendor/michael/laravelpagseguro/src/laravel/pagseguro/Checkout/SimpleCheckout.php", "line": 159, "function": "send", "class": "laravel\pagseguro\Remote\Checkout", "type": "->" },

Boa noite, também estou com este problema. Você conseguiu encontrar uma solução?

**Comment by jouglasw** [comment]
> Boa noite, também estou com este problema. Você conseguiu encontrar uma solução?

Infelizmente ninguém apontou uma possível causa. Nem aqui nem no (péssimo) suporte do PagSeguro.
Mas felizmente o problema parou de ocorrer sozinho. Só posso crer que tenha sido alguma instabilidade na API do PagSeguro.
Essa foi a segunda ou terceira vez que tive esse problema. Em todas só me restou esperar que normalizasse.

**Comment by jairdeon** [comment]
> > Boa noite, também estou com este problema. Você conseguiu encontrar uma solução?
> 
> Infelizmente ninguém apontou uma possível causa. Nem aqui nem no (péssimo) suporte do PagSeguro. Mas felizmente o problema parou de ocorrer sozinho. Só posso crer que tenha sido alguma instabilidade na API do PagSeguro. Essa foi a segunda ou terceira vez que tive esse problema. Em todas só me restou esperar que normalizasse.

Obrigado, @jouglasw, de fato aparentou ser uma instabilidade da API, fiz a ativação no sistema e tudo funcionou perfeitamente. Caso aconteça mais vezes, irei considerar como você sugeriu.. que seria aguardar, pois provavelmente deve ser alguma questão interna com o Pagseguro.

Mais uma vez, agradeço por ter me retornado.

**Comment by jouglasw** [comment]
Outra vez o mesmo problema... 🤦‍♂️
Outra vez de mãos atadas, sem suporte...
