### ISSUE TITLE
Documentação e tutoriais

### ISSUE THREAD

**Issue by marabesi** [michaeldouglas/laravel-pagseguro#30]
Criar um wiki, documentar melhor a API e fornecer também tutoriais para facilitar o uso da API

**Comment by tperrelli** [comment]
Na documentação tem sender' => array('senderEmail' => 'tteste@test.com'); Por algum motivo, desta forma, o DateHydrate seta como null. Para popular corretamente, tive que mudar a chave do array "senderEmail" apenas para email. Possivelmente, o mesmo problema deve acontecer em outros casos.

**Comment by marabesi** [comment]
@tperrelli creio que com a nova versão da API isso foi corrigido

**Comment by squaq** [comment]
Oi pessoal, 

Segui todos os passos da instalação e quando chamo a função PagSeguro::checkout() aparece o seguinte erro "Class 'App\Http\Controllers\PagSeguro' not found".
Eu já gastei um tempo tentando corrigir mas vocês podem me ajudar a resolver isso por favor?

**Comment by isaquesb** [comment]
@squaq, você deve estar tentando chamado de um controller qualquer com o namespace "App\Http\Controllers" porém sem usar o \PagSeguro para que a o laravel resolva com o facade da lib ao tentar fazer o autoload.
Tenta colocar \PagSeguro (com a barra) e posta aqui se deu certo.

**Comment by squaq** [comment]
não funcionou @isaquesb! Mesmo colocando o 'use App\Http\Controllers\PagSeguro;' deu o mesmo erro. O outro momento que chamo algo no controller é quando coloco 'use App\Http\Controllers\Controller;' e a propria classe tem um extends Controller.

**Comment by isaquesb** [comment]
@squaq, eu não quiz dizer para colocar o  "use App\Http\Controllers\PagSeguro", até porque essa classe não existe.
Eu disse para usar o facade do PagSeguro usando a barra invertida.

```
namespace  App\Http\Controllers;
// ....
class MyController extends Controller
{
     public function index()
     {
          // ....
          $checkout = \PagSeguro::checkout()->createFromArray($data);
     }
}
```

**Comment by marabesi** [comment]
@squaq por favor abra uma issue para essa sua dúvida, pois aqui é uma issue única e exclusiva para a documentação

**Comment by josebispo** [comment]
Como fica a rota para Route [pagseguro.redirect] not defined.
Na documentação tem a de notificações porém não fala nada da pagseguro.redirect !
o comando     $checkout = PagSeguro::checkout()->createFromArray($data); envia a requisição ou redireciona o usuário para o pagseguro ? att.

**Comment by isaquesb** [comment]
@josebispo.
É preciso criar uma nova issue para tirar dúvidas.
Mas já adiantando, é preciso criar uma rota com o nome "pagseguro.redirect" para ter para onde o pagseguro enviar o cliente de volta ao seu site após o pagamento. Caso você queria colocar uma URL qualquer manualmente, forneça a chave "redirectURL" mesmo que nula, no array $data do exemplo.

**Comment by marabesi** [comment]
Por favor, criem novas issues para qualquer assunto que não seja sobre a documentação. Caso contrário serei forçado a deletar os comentários aqui feitos

**Comment by josebispo** [comment]
@marabesi  o @isaquesb  já informou isso, desnecessário.
Já abri uma nova issue .

**Comment by marabesi** [comment]
@josebispo se você já viu que eu informei, por que mesmo assim escreveu algo não relacionado a isso ?

**Comment by josebispo** [comment]
Vou repetir @marabesi o @isaquesb já informou isso na minha pergunta, ficou claro agora.
