### ISSUE TITLE
Quando o token é inválido, deveria lançar uma exception do tipo TokenInvalido

### ISSUE THREAD

**Issue by tperrelli** [michaeldouglas/laravel-pagseguro#33]
No método _request na classe  laravel\pagseguro\Request\Request, quando o token é inválido, essa linha aqui "$result = curl_exec($this->curl);" retorna "Unauthorized". Até aí tudo bem. O problema é que logo após disso, o xml tenta ser carregado nessa linha "$xml = simplexml_load_string($result);",
gerando o erro a seguir.

![captura de tela 2015-12-10 as 08 27 38](https://cloud.githubusercontent.com/assets/1470890/11714279/ce9b5aac-9f17-11e5-9be8-93c8adde562f.png)

**Comment by michaeldouglas** [comment]
@tperrelli Esse erro foi ajustado na nova versão do Laravel PagSeguro, por favor, verificar.
