### ISSUE TITLE
Quando não definimos uma chave itemAmount1 não dispara erro

### ISSUE THREAD

**Issue by tperrelli** [michaeldouglas/laravel-pagseguro#34]
Quando não definimos uma chave itemAmount1 não dispara erro.
Ao utilizarmos a função request->getCode(), apenas retorna um SimpleXMLElement {#348} vazio sem informar o motivo. Essa validação poderia ser feita antes mesmo de bater na API do pagseguro.

**Comment by isaquesb** [comment]
Instale a nova versão. Ela não usa chaves para criar os items.
