### ISSUE TITLE
Quando o code é retornado, obtenho um SimpleXMLElement sem uma chave definida

### ISSUE THREAD

**Issue by tperrelli** [michaeldouglas/laravel-pagseguro#35]
![captura de tela 2015-12-10 as 09 54 51](https://cloud.githubusercontent.com/assets/1470890/11715824/f963a094-9f23-11e5-928f-346ab5bacb32.png)

Seria mais interessante se viesse a chave "code" e "date", pois dessa forma eu poderia acessar normalmente pelo javascript.

Do jeito que está hoje, sou obrigado a fazer um cast explícito pra array, pra aí sim conseguir obter o valor do code:

$code = (array) $code;
echo $code[0];

**Comment by eullercristian** [comment]
+1

**Comment by marabesi** [comment]
Adicionei no milestone para que seja implementado na próxima versão

**Comment by isaquesb** [comment]
A nova versão retorna um objeto com todos os dados.
