### ISSUE TITLE
sandbox = true no config não muda o endereço do checkout

### ISSUE THREAD

**Issue by Soufraz** [michaeldouglas/laravel-pagseguro#36]
Fiz algumas mudanças para adiantar o meu projeto. Mas gostaria de saber se a parametrização no `laravelpagseguro.php` em relação ao sandbox funciona em alguma versão de vocês.

O que percebi foi que, atualmente a requisição na api de produção, é no endereço `https://ws.pagseguro.uol.com.br/v2/checkout`. E a requisição na api de homologação, é no endereço `https://ws.sandbox.pagseguro.uol.com.br/v2/checkout`.
Porém, ao trocar a variável sandbox para true no `laravelpagseguro.php` as requisições continuam indo para `https://ws.pagseguro.uol.com.br/v2/checkout`.

Eu adicionei no construct de `Request/Request.php` e `Request/PaymentRequest.php` a seguinte atribuição:
`$this->_setURL(Config('laravelpagseguro.url'));`. E resolveu o meu problema.

Gostaria de saber se existe alguma issue em andamento para a resolução deste problema. Ou se posso duplicar o projeto composer para eu não perder após os `composer update`. Pois não achei nada que faça a  mudança das variáveis.

Pra finalizar, meu `laravelpagseguro.php` ficou (por enquanto) assim:

```
$env = 'sandbox';
if($env == 'sandbox'){
    $url = 'https://ws.sandbox.pagseguro.uol.com.br/v2/checkout';
    $token = 'ASFD7896ASFD7896ASFD7896ASFD7896';
}else if($env == 'prod'){
    $url = 'https://ws.pagseguro.uol.com.br/v2/checkout';
    $token = 'ASFD7896ASFD7896ASFD7896ASFD7896';
}

return [
    'sandbox' => true,//DEFINI SE SERÁ UTILIZADO O AMBIENTE DE TESTES
    
    'credentials' => [//SETA AS CREDENCIAIS DE SUA LOJA
        'email' => 'email@gmail.com',
        'token' => $token
    ],
    'currency' => [//MOEDA QUE SERÁ UTILIZADA COMO MEIO DE PAGAMENTO
        'type' => 'BRL'
    ],
    'reference' => [//CRIAR UMA REFERENCIA PARA OS PRODUTOS VENDIDOS
        'idReference' => null
    ],
    'url' => $url,
];

```

**Comment by marabesi** [comment]
Hoje infelizmente está fixo a utilização da url. Mas para apróxima versão já vamos implementar essa feature, se rolar algum pull request ou tempo livre poderemos ter até antes !

Valeu @Soufraz !

**Comment by isaquesb** [comment]
Sendo trabalhado na branch notification.

**Comment by Soufraz** [comment]
Opa.. Maravilha.  :D

**Comment by paulocastellano** [comment]
Alguma previsão de quando será feito o merge do notification pro master com esse update?

**Comment by marabesi** [comment]
creio que em duas semanas teremos o resultado da nova branch

**Comment by isaquesb** [comment]
Resolvido.
