### ISSUE TITLE
Não consegue inserir no Array o email do comprador

### ISSUE THREAD

**Issue by brunofonseca** [michaeldouglas/laravel-pagseguro#38]
Olá!

Estou a utilizar o pacote. Eu coloco todas a informações corretamente nele , via formulário devidamente preenchido e validado em meu site. Porém ao criar a chamada ao PagSeguro, conforme no exemplo, ele processa e retorna do próprio site do PagSeguro , que não foi informado o e-mail.

O que pode esta ocorrendo?

**Comment by isaquesb** [comment]
@brunofonseca , iremos verificar o problema. Provavelmente algum conflito com o nome das chaves entre "senderEmail" e "email".
Já estamos trabalhando numa nova branch para lançar um release mais estável após a virada de ano.

Abs.

**Comment by marabesi** [comment]
@brunofonseca manda o array de exemplo que vc está usando, ou ele é exatamente igual o que está no README ?

**Comment by marabesi** [comment]
teste

**Comment by brunofonseca** [comment]
Exatamente igual.
Em 30/12/2015 5:39 PM, "Matheus Marabesi" <notifications@github.com>
escreveu:

**Comment by marabesi** [comment]
@brunofonseca como a lib foi atualizada creio que essa issue não exista mais, se o problema persistir por favor @brunofonseca  abra ela novamente
