### ISSUE TITLE
laravel v5.2.3 ?

### ISSUE THREAD

**Issue by thusk** [michaeldouglas/laravel-pagseguro#39]
Olá amigo, estava buscando um provider do Pagseguro para Laravel , e na instalação das versões mais recentes do Laravel não é possível por causa do laravel/support 

    - michael/laravelpagseguro 0.4.1 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].

Existe alguma diferença drástica na interface do laravel/support 5.1.8 e laravel/support 5.2.x ?

existe alguma previsão para atender o laravel 5.2.x ?

grato desde já Daniel

**Comment by marabesi** [comment]
Fizemos uma atualização na lib e já está ok com o laravel 5.2 :)

Só diga se consegue instalar agora para fecharmos a issue

**Comment by thusk** [comment]
Mesmo erro, você atualizou o packagist? 

    - michael/laravelpagseguro 0.4.1 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].

notei no teu commit que você mexeu no composer.json , mas no packagist  ainda é  o anterior (creio eu)


atenciosamente Daniel.

**Comment by thusk** [comment]
realmente , mudei para uma pasta vazia, limpei cachê , dei um require e o composer.json continua:
falta só atualizar no packagist

```json
{
    "name": "michael/laravel-pagseguro",
    "description": "Biblioteca de integração com o gateway de pagamento PagSeguro.",
    "keywords": ["framework", "laravel", "Gateway Pagamento", "PagSeguro"],
    "license": "MIT",
    "type": "library",
    "require": {
        "php": ">=5.4.0",
        "ext-curl": "*",
        "lib-curl": "*",
        "lib-openssl": "*",
        "lib-libxml": "*",
        "illuminate/support": "5.1.*"
    },
    "require-dev": {
        "phpunit/phpunit": "4.0.*"
    },
    "autoload": {
        "psr-0":{
            "laravel\\pagseguro\\": "src/"
        }
    },
    "authors": [
        {
            "name": "Michael Douglas Barbosa Araujo",
            "email": "michaeldouglas010790@gmail.com"
        },
        {
            "name": "Isaque de Souza",
            "email": "isaquesb@gmail.com"
        }
    ],
    "config":{
        "bin-dir": "bin/"
    },
    "minimum-stability": "dev"
}
```

grato Daniel

**Comment by marabesi** [comment]
Chegou a limpar o cache do composer? Testamos aqui com as versẽos 5.1 e 5.2 do laravel e tudo está ok.

ping @michaeldouglas

**Comment by thusk** [comment]
dei um composer clear-cache e esse foi o composer.json que carregou ._.

**Comment by thusk** [comment]
abri em uma maquina windows, que nunca tinha tentando baixar esse pacote.. e..
```json
{
    "name": "michael/laravel-pagseguro",
    "description": "Biblioteca de integração com o gateway de pagamento PagSeguro.",
    "keywords": ["framework", "laravel", "Gateway Pagamento", "PagSeguro"],
    "license": "MIT",
    "type": "library",
    "require": {
        "php": ">=5.4.0",
        "ext-curl": "*",
        "lib-curl": "*",
        "lib-openssl": "*",
        "lib-libxml": "*",
        "illuminate/support": "5.1.*"
    },
    "require-dev": {
        "phpunit/phpunit": "4.0.*"
    },
    "autoload": {
        "psr-0":{
            "laravel\\pagseguro\\": "src/"
        }
    },
    "authors": [
        {
            "name": "Michael Douglas Barbosa Araujo",
            "email": "michaeldouglas010790@gmail.com"
        },
        {
            "name": "Isaque de Souza",
            "email": "isaquesb@gmail.com"
        }
    ],
    "config":{
        "bin-dir": "bin/"
    },
    "minimum-stability": "dev"
}
```
