### ISSUE TITLE
Gerar ID de Sessão para o checkout transparente

### ISSUE THREAD

**Issue by nunesbeto** [michaeldouglas/laravel-pagseguro#42]
É possível, com esta biblioteca, gerar o ID de sessão necessário para o checkout transparente? 
Segue a referência para o que estou dizendo: https://pagseguro.uol.com.br/v2/guia-de-integracao/tutorial-da-biblioteca-pagseguro-em-php.html#checkout-transparente

**Comment by marabesi** [comment]
Até onde eu sei não, procede ? @michaeldouglas @isaquesb

**Comment by michaeldouglas** [comment]
@nunesbeto Eu desenvolvi um comando que irá retornar, por favor, testar:
php artisan pagseguro:sessao-pagamento

Caso estaja correto, desenvolvo um método para retornar o ID de sessão.

**Comment by marabesi** [comment]
ab832b6
