### ISSUE TITLE
Call to undefined method laravel\pagseguro\Request\SessionPaymentRequest::get()

### ISSUE THREAD

**Issue by fwbeck** [michaeldouglas/laravel-pagseguro#44]
Com laravel 5.2 rodei o código de exemplo apenas para ver se estava tudo ok, inseri o email e token.
Quando tento rodar aparece o seguinte:

FatalErrorException in helpers.php line 625: Call to undefined method laravel\pagseguro\Request\SessionPaymentRequest::get()

Se faço um dd($code) no controller exibe:
SimpleXMLElement {#255 ▼
  +"0": "A60CF14DBBBB8BD774EF2FA07BD80780"
}
(o que aparentemente parece q faz o request)

**Comment by isaquesb** [comment]
Checkout transparente será implementado na próxima versão. Completo.

**Comment by marabesi** [comment]
Checkout transparente será implementado em uma versão futura, mas não sabemos a data ainda.
