### ISSUE TITLE
Recuperar Pedido.

### ISSUE THREAD

**Issue by hkanata** [michaeldouglas/laravel-pagseguro#45]
Ola pessoal. Estou usando essa biblioteca fantástica. Porém não sei como recuperar um pedido.
Como devo proceder?
Obrigado

**Comment by marabesi** [comment]
Como assim recuperar um pedido @hkanata  ? Você diz os dados que foram enviados para o pagseguro ?

**Comment by hkanata** [comment]
Isso mesmo @marabesi gostaria de recuperar.
Eu enviei o codigo identificador do produto, gostaria de recuperar o pedido pois o código do produto está neste pedido do pagseguro, preciso pegar o status e atualizar o pedido no meu banco.
obrigado

**Comment by marabesi** [comment]
ping não tenho certeza se essa versão comporta isso mas o  @isaquesb consegue nos dar certeza

**Comment by marabesi** [comment]
@hkanata a lib foi atualizada e acho que tem a feature que você precisa, veja https://github.com/michaeldouglas/laravel-pagseguro#consultando-uma-transa%C3%A7%C3%A3o-manualmente

**Comment by hkanata** [comment]
@marabesi muito obrigado. Um grande abraço

**Comment by marabesi** [comment]
Vou fechar a issue aqui qualquer coisa só abrir de novo
