### ISSUE TITLE
laravelpagseguro.php

### ISSUE THREAD

**Issue by vagner107** [michaeldouglas/laravel-pagseguro#46]
Boa Noite, 

Quero saber se há a possibilidade de injetar direto o e-mail e o Token do Pagseguro.
Diferente do config, que insere apenas uma na configuração, ao invés inserir ao meu querer.

Possível?

**Comment by isaquesb** [comment]
Vagner, este final de semana iremos publicar um novo release que já conta com essa possibilidade.
Será possível trocar as credenciais conforme a necessidade.

**Comment by marabesi** [comment]
Irei fechar a issue pois a dúvida parece que foi sanada, @vagner107 fique de olho aqui para quando a nova versão for lançada :)
