### ISSUE TITLE
Composer não está pegando a versão mais recente do repositorio git?

### ISSUE THREAD

**Issue by rodrigonsh** [michaeldouglas/laravel-pagseguro#48]
A documentação do projeto fala sobre Platform\Laravel5 só que o pacote que vem pelo composer não possui estas estruturas de pastas

Alguma ideia?

**Comment by rodrigonsh** [comment]
A solução foi especificar o repositorio diretamente no composer.json

```
"repositories": [
        {
			"type": "vcs",
            "url": "https://github.com/michaeldouglas/laravel-pagseguro.git"
        }
    ],
```


e depois modificar o require, só que tem um porém, no composer.json do github o projeto esta com nome ** "michael/laravel-pagseguro"**

**Comment by marabesi** [comment]
Você conseguiu instalar a versão 1.0.* da lib ? Encontrei um problema aqui ao tentar instalar

**Comment by leohmoraes** [comment]
Fiz a instalacao padrao usando o require,
$php artisan vendor:publish
e depois tentei pelas dicas do Rodrigo
acontece em ambos o seguinte erro:
Can't locate path: </home/vagrant/sites/api/vendor/michael/laravelpagseguro/src/laravel/pagseguro/Platform/Laravel5/config/laravelpagseguro.php>

**Comment by marabesi** [comment]
@leohmoraes tente de novo a instalação pelo composer, tinha um erro no packagist mas agora já está tudo ok.

Se o erro persistir nos avise

**Comment by isaquesb** [comment]
@leohmoraes 
Corrigi aqui o bug com o caminho de pasta.
Após mover o ServiceProvider de local acabei deixando o caminho antigo.

**Comment by isaquesb** [comment]
@leohmoraes 
Esqueci de falar, aponta pra dev-master em vez da 1.* pra pegar com o bug corrigido.

**Comment by rodrigonsh** [comment]
O fix no packagist resolveu tudo. Muito obrigado
