### ISSUE TITLE
Classe de geração de logs

### ISSUE THREAD

**Issue by michaeldouglas** [michaeldouglas/laravel-pagseguro#5]
Classe e salvamento dos logs de erro ou de geração de requisição de compra.

**Comment by xshifty** [comment]
@michaeldouglas Vou analisar essa issue, depois te mando um draft.

**Comment by xshifty** [comment]
@michaeldouglas você já tem em mente algo para essa feature?

**Comment by michaeldouglas** [comment]
@xshifty Manda as suas sugestões !
