### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by hkanata** [michaeldouglas/laravel-pagseguro#51]
Está dando este erro na nova biblioteca.
ErrorException in Resolver.php line 64:
array_key_exists() expects parameter 2 to be array, null given

**Comment by isaquesb** [comment]
@hkanata , seu config laravelpagseguro.php esta na mesma estrutura do laravel\pagseguro\Config\applicationconfig.php?
Você instalou agora ou fez migração do 0.5 pra o 1.0 dev-master?
Se fez migração, da uma verificada no config porque mudou bastante a estrutura.

**Comment by hkanata** [comment]
@isaquesb pois é. Mudou bastante mesmo. Foi só atualizar que deu um bocado de problema aqui.
Eu fiz isso, mas vou refazer desinstalando novamente. Obrigado pela ajuda.

**Comment by marabesi** [comment]
vou fechar então a issue, qualquer coisa so abrir novamente : )
