### ISSUE TITLE
Route [pagseguro.redirect] not defined.

### ISSUE THREAD

**Issue by ricardotomim** [michaeldouglas/laravel-pagseguro#53]
Boa tarde

Estou tentando implementar mas sempre dar erro

Route [pagseguro.redirect] not defined.

Obs: a rota foi existe.

Grato

**Comment by isaquesb** [comment]
@ricardotomim,
Não entendi se esse "foi" significa "não existe" ou "existe".
Caso a rota exista, consegue acessar ela de um lugar qualquer como por exemplo?:
```
echo \URL::route('pagseguro.redirect');
```
Esse nome esta padrão no config, mas nunca foi exigido nas vezes que usei.
Tenta deixar como nulo por exemplo:
```
'routes' => [
       'redirect' => [
             'route-name' => null,
       ],
.....
```
Para que ele não tente resolver esse nome.
Porém nesse caso, você ficaria sem URL de retorno.

**Comment by ricardotomim** [comment]
Oi Isaque, desculpe o erro na digitação, o "foi" significa "existe", rsrs.

Consigo acessar a rota sim.

Uma pergunta: estou querendo utilizar o [PagSeguro Lightbox](https://pagseguro.uol.com.br/receba-pagamentos.jhtml#checkout-lightbox) é possível ?

Abraços

**Comment by isaquesb** [comment]
@ricardotomim ,

O problema da rota foi resolvido ou continua apresentando esse erro?
Na verdade não estava muito por dentro desse modo lightbox.
Vamos implementar o checkout transparente logo mais, ai aproveitaremos para verificar esse modo também.

**Comment by ricardotomim** [comment]
Isaque, devido a urgência de concluir o projeto (como sempre né, rs), acabei optando pela biblioteca do pagseguro mesmo.

Mas estarei acompanhando e testando quando liberarem o checkout transparente.

Obs; o lightbox é legal, porque é bem simples de implementar e cria um modal no site mesmo.

Grato

**Comment by marabesi** [comment]
@ricardotomim já que você resolveu seu problema de outra forma vou fechar a issue aqui

**Comment by rs-benatti** [comment]
Estou com o mesmo problema
