### ISSUE TITLE
encoding, Acentuação.

### ISSUE THREAD

**Issue by laerciocrestani** [michaeldouglas/laravel-pagseguro#55]
Pessoal, estou passando os parâmetros:

> 'sender' => [
> 'email' => ''.$cadastro->email.'',
> 'name' => 'Laércio Crestani',

O erro é
Error on send: 400-<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>Malformed request XML: {0}.</code><message>Malformed request XML: XML document structures must start and end within the same entity..</message></error></errors>

Creio que seja a parte da acentuação. Alguém tem alguma alternativa?

**Comment by marabesi** [comment]
Ja tentou tirar o acento do nome ?

**Comment by laerciocrestani** [comment]
Sim, já tirei e funciona perfeitamente, gostaria de saber se é padrão do pagseguro  sem acentuaçnao ou devo trocar o encoding dele

**Comment by xshifty** [comment]
https://blogpagseguro.com.br/2012/03/acentuacao-da-descricao-do-seu-produto-apareceu-errada-veja-como-solucionar/

Nesse link explica que a codificação padrão do pagseguro é iso-8859-1, se tu enviar os dados em outro formato, ele vai dar problema mesmo.

Tente codificar a string para esse formato. Creio que um utf8_decode já resolva.
Mas recomendo o uso da iconv.

**Comment by xshifty** [comment]
@laerciocrestani resolveu?

**Comment by laerciocrestani** [comment]
Pois é... A minha App esta toda em UTF-8 se utilizo o **iconv** ele fica desta forma:

Laércio Crestani = La?rcio Crestani.

usei uma function desta forma:

> function removeAcentuacao($string) {
>$string = htmlentities($string, ENT_COMPAT, 'UTF-8');
>$string = preg_replace('/&([a-zA-Z ])(uml|acute|grave|circ|tilde|cedil|amp|rdm|rdf);/', '$1',$string);
>return html_entity_decode($string);
>}

Deu certo aqui...

**Comment by isaquesb** [comment]
@laerciocrestani 

Acabei de subir uma correção para resolver esse seu problema.
Pode usar acentos em UTF-8 normalmente agora.
