### ISSUE TITLE
shipping -> cost

### ISSUE THREAD

**Issue by laerciocrestani** [michaeldouglas/laravel-pagseguro#56]
Olá. Tenho da seguinte forma:

>'shipping' => [
>			        'address' => [
>			            'postalCode' => ''.removePontuacao($cadastro->cep).'',
>			            'street' => ''.removeAcentuacao($cadastro->endereco).'',
>			            'number' => ''.removePontuacao($cadastro->numero).'',
>			            'district' => ''.removeAcentuacao($cadastro->bairro).'',
>			            'city' => ''.removeAcentuacao($cadastro->cidade).'',
>			            'state' => 'RS',
>			            'country' => 'BRA',
>			        ],
>			        'type' => 1, #1-PAC, 2-SEDEX, 3-GRATUITO
>			        'cost' => 16.9,
>			    ],

No checkout do pag seguro não aparece nada, **somente se coloco nos meus items.**
...
'shippingCost' => 10,90,
...
neste caso aparece PAC => R$ 10,90

Alguém conhece o motivo?

**Comment by isaquesb** [comment]
@laerciocrestani 

Bug Corrigido nos últimos commits.
Favor baixar a última versão (composer update)

Corrigi também o problema com acentuações informado por você no #55
