### ISSUE TITLE
Mudança de status do pedido no pagseguro.

### ISSUE THREAD

**Issue by josebispo** [michaeldouglas/laravel-pagseguro#59]
Bom dia como consultar as mudanças de status sem ser manualmente ?

**Comment by isaquesb** [comment]
@josebispo ,

Tem como receber pelo módulo de notificação:
https://github.com/michaeldouglas/laravel-pagseguro#recebendo-notifica%C3%A7%C3%B5es-de-transa%C3%A7%C3%A3o
