### ISSUE TITLE
InvalidArgumentException on key: Id quando tem apenas um item no pagamento

### ISSUE THREAD

**Issue by nunomazer** [michaeldouglas/laravel-pagseguro#64]
Quando um pagamento tem apenas um item eu estava recebendo esta exceção, ao verificar encontrei o problema da classe ItemCollection criar um iterator nos dados recebidos, porém quando apenas um item existe, os dados não são um array multidimensional e o teste do item corrente gera o erro.

**Comment by isaquesb** [comment]
Obrigado pela análise e por reportar @nunomazer .
Problema com único item resolvido.
