### ISSUE TITLE
Invalid Transaction Code

### ISSUE THREAD

**Issue by adrianowead** [michaeldouglas/laravel-pagseguro#66]
Pessoal, boa tarde!

Desculpem caso eu esteja falando alguma besteira, mas é a primeira vez que estou utilizando esta biblioteca para integração com o PagSeguro.

Estou testando em ambiente sandbox, a submissão foi ok, o problema está na consulta da transação, recebo o seguinte erro:

InvalidArgumentException in Transaction.php line 74:
Invalid transaction code

Vi que neste documento tem a seguinte validação:
if (!\is_string($code) || \strlen($code) != 36)

Mas no ambiente de sandbox, minhas transações geram códigos de 32 dígitos e não 36.

Não sei se em produção o comprimento deste código muda para 36.

Se puderem modificar essa validação, eu agradeço muito.

Abraços :)

**Comment by isaquesb** [comment]
Removido.

É que no manual esta descrito 36 porque segue esse padrão:
B8DF6CBD-C48D-4BCC-B318-08D30D2EBBC3
Mas usando sem os traços da máscara também funciona, por isso removi:
B8DF6CBDC48D4BCCB31808D30D2EBBC3

Já testei aqui.

**Comment by isaquesb** [comment]
Obs.: Use a dev-master para resgatar o ajuste.
Em breve lançaremos novo release com mais correções / novidades.
