### ISSUE TITLE
Recebimento de código de checkout em nova versão

### ISSUE THREAD

**Issue by Soufraz** [michaeldouglas/laravel-pagseguro#69]
Rodei o composer update e o pacote estava em modo de desenvolvimento no composer.json.
Atualizou o pacote e estou aproveitando para utilizar a versão nova.
Porém, alguns itens estão sem ligação na documentação.
Na versão do pacote que eu estava utilizando, eu precisava pegar o código de checkout para checkout via lightbox. Era feito assim:

```
$request = PagSeguro::setRequest($pagseguro_data);
$request->sendRequest();
$code = $request->request->getCode();
```

Na versão atual, o pacote diz que para eu fazer o checkout, eu preciso utilizar isso:
```
$checkout = PagSeguro::checkout()->createFromArray($data);
```

E logo após, diz que para confirmar a transação, eu preciso utilizar isso:
```
$information = $request->send($credentials);
if ($information) {
    print_r($information->getCode());
    print_r($information->getDate());
    print_r($information->getLink());
}
```
Sendo que o objeto checkout não contem nenhum método ou atributo de retorno com o nome de request, como faz para eu obter o request nessa nova versão do pacote?

A documentação ficou pouco clara. Existe alguma documentação externa ou tutorial que fale mais sobre os recursos do pacote?

**Comment by Soufraz** [comment]
Para os que estão passando pelo mesmo problema, é só uma questão de nomenclatura na documentação. Segue a solução:

```
$checkout = PagSeguro::checkout()->createFromArray($data);
        $credentials = PagSeguro::credentials()->get();

        $information = $checkout->send($credentials);
        if ($information) {
            print_r($information->getCode());
            print_r($information->getDate());
            print_r($information->getLink());
        }
```

**Comment by isaquesb** [comment]
Obrigado pelo feedback @Soufraz 
Logo mais lançaremos mais algumas features no pacote. Não deixe de acompanhar.
Documentação atualizada.
Vw!
