### ISSUE TITLE
Carrinho de compras

### ISSUE THREAD

**Issue by michaeldouglas** [michaeldouglas/laravel-pagseguro#7]
Criação de um carrinho de compras para utilização do usuário que utilizar a biblioteca.

**Comment by sergiopeluzzi** [comment]
Tem esse carrinho aqui que um amigo meu fez: https://github.com/juliobitencourt/laravel-cart
Na documentação só faltou como fazer a injeção da classe no construtor, mas ele vai fazer em breve

**Comment by isaquesb** [comment]
Será feito numa outra lib.
