### ISSUE TITLE
Erro 'Invalid document data' na notificação do sandbox

### ISSUE THREAD

**Issue by TopFuel** [michaeldouglas/laravel-pagseguro#70]
Olá, estou recebendo um erro quando o sandbox do pagseguro me envia uma notificação sobre uma transação.
Parece que o problema é que o sandbox envia o CPF junto com as informações da transação e a função [documentFactory na classe DocumentCollection](https://github.com/michaeldouglas/laravel-pagseguro/blob/46b13d749b4190ef19f5844d2408aa310d2880ac/src/laravel/pagseguro/Document/DocumentCollection.php#L53-L64) procura por [**type** e **number**](https://github.com/michaeldouglas/laravel-pagseguro/blob/46b13d749b4190ef19f5844d2408aa310d2880ac/src/laravel/pagseguro/Document/DocumentCollection.php#L55-L58), porem o sandbox envia **type** e **value**.

```
<sender>
    ...
    <documents>
        <document>
            <type>CPF</type>
            <value>83654761500</value>
        </document>
    </documents>
</sender>
```

Usando no modo de produção este erro não aparece pois o CPF não é enviado pelo pagseguro.

**Comment by isaquesb** [comment]
Vou analisar e logo mais aplico a correção se necessário.

**Comment by TopFuel** [comment]
Ok obrigado, fico no aguardo.

**Comment by isaquesb** [comment]
@TopFuel , desculpe a demora.
Problema resolvido no último commit.
Por enquanto disponível no dev-master, em breve será lançado novo release com todos os últimos problemas.
