### ISSUE TITLE
Notification SandBox

### ISSUE THREAD

**Issue by f0ntana** [michaeldouglas/laravel-pagseguro#71]
Eu tentei pegar a notificação utilizando o sandbox, mas sem sucesso quando utilizei produção deu certo...
Será que é algo no sandbox?

**Comment by TopFuel** [comment]
Sim, eu abri uma issue sobre o mesmo problema #70

**Comment by isaquesb** [comment]
@f0ntana 
Problema corrigido (para dev-master) de acordo com a issue #70 .
