### ISSUE TITLE
Venda para pessoa jurídica

### ISSUE THREAD

**Issue by Frossard** [michaeldouglas/laravel-pagseguro#72]
Bom dia, como faço para vender para pessoa jurídica? Não consigo preencher o cnpj em documents, está retornando erro. Exemplo:

```
'documents' => [
            [
                'number' => '06220747000131',
                'type' => 'CNPJ'
            ]
        ],
```

Estou precisando que quando redireciono para o link de pagamento não apareça CPF do dono do cartão, e sim CNPJ do dono do cartão. Estou vendendo para PF e PJ. Como posso fazer?

Fico no aguardo.
Obrigado.

**Comment by isaquesb** [comment]
@Frossard ,

Na documentação da API mesmo, eles dizem que só permitem CPF nesse campo.
https://pagseguro.uol.com.br/v2/guia-de-integracao/api-de-pagamentos.html#!v2-item-api-de-pagamentos-parametros-http

Veja em "Tipo de documento do comprador."
