### ISSUE TITLE
Alguns parâmetros não estão sendo recebidos

### ISSUE THREAD

**Issue by fhb12345** [michaeldouglas/laravel-pagseguro#73]
Notamos que alguns parâmetros deixaram de serem recebidos pelo PagSeguro, algumas lojas deixaram de trazer o campo 'postalCode', no PagSeguro, ao entrar ele está pedindo agora para informar o CEP ao invés de trazer o mesmo já preenchido, sintaxe utilizada:

```php
'shipping' => [
        'address' => [
            'postalCode' => '12345678',
        ],
    ],
```

Outro campo é o de telefone, estou enviando assim:
```php
'sender' => [
        'phone' => '0012345678',
    ]
```

Onde 00 é o ddd e 12345678 é o telefone, o postalCode estava sendo enviado a um tempo atras, o phone eu não me recordo....

**Comment by isaquesb** [comment]
@fhb12345 

Você esta dizendo que informa isso no envio, mas a integração não repassa ao PagSeguro, fazendo com que a informação seja exigida novamente ao comprador?
Qual versão da lib você esta usando?

**Comment by fhb12345** [comment]
**Versão da Lib**
O composer está pegando a versão do commit ```915d455```, pelo que eu vi é o mais recente, 

composer.json:
```json
"require": {
    "michael/laravelpagseguro": "dev-master"
}
```

@isaquesb 
Isso mesmo, a informação é exigida novamente ao comprador, CEP e Telefone,

**Comment by isaquesb** [comment]
@fhb12345 

Vou verificar aqui se há alguma diferença sobre isso entre o sandbox e a produção sobre as chaves do XML.
Logo mais eu publico uma correção e dou um feedback.
Vlw.

**Comment by marabesi** [comment]
issue respondida, no aguardo do @isaquesb
