### ISSUE TITLE
Checkout Transparente

### ISSUE THREAD

**Issue by guilhermeperin** [michaeldouglas/laravel-pagseguro#78]
Olá Pessoal!

Como faço para implementar o checkout transparente?
Obrigado!

**Comment by marabesi** [comment]
@guilhermeperin ainda não temos essa opção, isso vai vir na próxima versão.

ping @isaquesb @michaeldouglas

**Comment by ealves** [comment]
Comecei a fazer e pra mim está atendendo perfeitamente, mas ainda faltam várias melhorias e ajustes. Fiz um trunk caso queira usar @guilhermeperin.

**Comment by guilhermeperin** [comment]
@ealves Obrigado pela resposta. É possivel ter acesso ao seu repositório?
Agradecido!

@marabesi valeu pela atenção!

**Comment by ealves** [comment]
@guilhermeperin https://github.com/ealves/laravel-pagseguro

**Comment by guilhermeperin** [comment]
@ealves Muito obrigado!

**Comment by marabesi** [comment]
@ealves pq não manda um pr aqui pra gente ? tem muitos outrs qu querem essa feature tb :))

**Comment by ealves** [comment]
@marabesi mandei mas foi rejeitado devido algumas PSR e melhorias.

**Comment by novasky** [comment]
@ealves Como eu poderia utilizar o seu método de envio transparente? Você tem ele publicado no packagist para que eu possa chamá-lo no composer?

@isaquesb @marabesi  Vocês ainda pensam em atualizar esse pacote com o checkout transparente?

Grande abraço.

**Comment by marabesi** [comment]
@novasky sim o checkout transparente é um dos goals aqui da api.

@ealves vou dar uma olhada na branch então e ver o que consigo fazer : )
