### ISSUE TITLE
Notification na Sandbox não retorna CPF e data de nascimento

### ISSUE THREAD

**Issue by Biscuri** [michaeldouglas/laravel-pagseguro#79]
Quando recebo notificações de transação, na variável $information, o Sender é recebido desta forma (estou testando com um comprador não cadastrado no Pagseguro, supostamente comprando pela primeira vez):

[sender:protected] => laravel\pagseguro\Sender\Sender Object
        (
            [email:protected] => c34176422338361817223@sandbox.pagseguro.com.br
            [name:protected] => Teste dos Santos
            [phone:protected] => laravel\pagseguro\Phone\Phone Object
                (
                    [areaCode:protected] => 42
                    [countryCode:protected] => 55
                    [number:protected] => 924983559
                    [validator:protected] => 
                )

            [documents:protected] => 
            [bornDate:protected] => 
            [validator:protected] => 
        )

Como pode-se perceber, as posições documents e borndate estão vazias. Eu gostaria de recuperar o CPF do usuário que fez a transação para identificá-lo quando recebo a notificação. Isso é mais um problema da sandbox do pagseguro, ou algum bug da biblioteca? Quando envio o CPF o Pagseguro está recebendo e auto-completando o formulário normalmente, o problema é só na notificação.

**Comment by isaquesb** [comment]
@Biscuri ,

A API de notificações do PagSeguro não informa essas informações.
Pode verificar no link: https://pagseguro.uol.com.br/v3/guia-de-integracao/api-de-notificacoes.html#v3-item-servico-de-notificacoes

Em: Transaction > Sender
