### ISSUE TITLE
Informações do cliente não vai para o pagseguro

### ISSUE THREAD

**Issue by matheusdavidson** [michaeldouglas/laravel-pagseguro#8]
Consegui usar o seu package, porem os dados do cliente não estão indo para o pagseguro.
Fiz um teste com as configurações da documentação e mesmo assim não funcionou, pode me ajudar?

**Comment by michaeldouglas** [comment]
Matheus, desculpa a demora. 

Então eu já identifiquei que existe um erro na Laravel PagSeguro e ajustei por enquanto o nome do cliente o restante eu irei trabalhar com o mesmo ajuste que fiz para que seja possível enviar esses dados!

 - Aproveitando eu também atualizei a Laravel PagSeguro, para o Laravel 5.0 e 5.1 está sobe o release 0.4.0 e 0.5.0 sendo assim a partir de agora a Laravel PagSeguro irá acompanhar as atualizações do Laravel.

Um grande abraço e deixarei sua issue aberta e quando concluir os outros dados de cliente aviso aqui e em seguida fecho essa issue.

**Comment by michaeldouglas** [comment]
Matheus,

Os ajustes que eu tinha comentado foram feito na versão 0.4.1 qualquer erro novamente, por favor, crie uma issue descrevendo o que ocorreu.

Obrigado e abraços.
