### ISSUE TITLE
Não recebo notificações

### ISSUE THREAD

**Issue by modugno** [michaeldouglas/laravel-pagseguro#80]
Boa noite Galera,
Eu não estou conseguindo receber as notificações, não sei se é erro meu, ou realmente não está funcionando..

Segue meu código

**laravelpagseguro.php**

```

'routes' => [
        'redirect' => [
            'route-name' => 'pagseguro.redirect', // Criar uma rota com este nome
        ],
        'notification' => [
            'callback' => function($information) {
                \Log::debub(print_r($information, 1));
            }, // Callable
            'credential' => 'default',
            'route-name' => 'pagseguro.notification', // Nome da rota
        ],
    ],
```

**routes.php**

```
Route::get('/pagseguro/redirect', [
        'uses' => 'SiteController@pagseguroDone',
        'as' => 'pagseguro.redirect',
    ]);

    Route::post('/pagseguro/notification', [
        'uses' => '\laravel\pagseguro\Platform\Laravel5\NotificationController@notification',
        'as' => 'pagseguro.notification',
    ]);

```

Outra obsevação, depois de finalizar ele não volta pro meu site, ele continua na pagsguro, estou testando em Sandbox.

**Comment by isaquesb** [comment]
@modugno 

Talvez não esta recebendo porque esta errado o nome do método no seu código. Esta "\Log::debub" em vez de "\Log::debug".

Quanto ao redirecionamento parece ok a configuração. Geralmente depois que é finalizado o pagseguro redireciona para seu site em 10 segundos. Esse problema continua mesmo?
