### ISSUE TITLE
Produto Digital

### ISSUE THREAD

**Issue by adrianoGaspar** [michaeldouglas/laravel-pagseguro#82]
Opa, bom dia a todos.
Eu consigo fazer a venda e entrega automática de produtos digitais com esse pacote? Se sim, poderiam colocar um exemplo de como utilizar por favor?

Valeu

**Comment by isaquesb** [comment]
@adrianoGaspar 

Quando você diz produtos digitais esta querendo dizer "sem frete" certo?
Nesse caso pode definir que o frete é zero e o tipo é "desconhecido":
```
  'shipping' => [
        'type' => \laravel\pagseguro\Shipping\ShippingInterface::TYPE_UNKNOW, // 3
        'cost' => 0,
   ],
```

**Comment by adrianoGaspar** [comment]
Opa, obrigado pela resposta. Tenho uma dúvida também com relação ao retorno do pagseguro. Vi que devo criar uma rota de retorno, devo configurar essa rota no pagseguro ou ele vai sempre retornar na rota indicada pelo tutorial? Se puderem esclarecer isso agradeço.

**Comment by isaquesb** [comment]
@adrianoGaspar 

Ele sempre vai direcionar você para esta rota, pois ele informa o endereço ao pagseguro automaticamente quando você envia o checkout.
Mas cuidado para não confundir a rota de redirecionamento com a rota de retorno.
A de redirecionamento é a página pra onde ele vai ao finalizar o pagamento e voltar ao seu site.
A de retorno é onde o PagSeguro faz o POST com informações atualizadas sobre esta transação.
