### ISSUE TITLE
Como recuperar dados da compra?

### ISSUE THREAD

**Issue by Denisbeder** [michaeldouglas/laravel-pagseguro#83]
Como recuperar dados da compra quando passar o notificationCode na rota de notificacao.
A ideia é quando meu sistema for notificado ele saber qual o status da compra, tipo saber se o pagamento foi aprovado ou nao.

Quando passo o codigo de notificacao recebo esse erro:

```
RuntimeException in Transaction.php line 81:
Error on getStatus: 400-<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>13003</code><message>invalid transactionCode value: 42527A579D489D48A3D994249FB735344ACE</message></error></errors>

```
Meu código:
```
public function notification(Request $request)
{
  $code_notification = $request->notificationCode;
  $credentials = PagSeguro::credentials()->get();
  $transaction = PagSeguro::transaction()->get($code_notification, $credentials);
  $information = $transaction->getInformation();

  dd($information);
}
```

**Comment by Denisbeder** [comment]
`$P`

**Comment by apsferreira** [comment]
Olá Denis, você conseguiu retornar? estou com o msm problema.

Obrigado.

**Comment by Denisbeder** [comment]
Tenha certeza que a rotas que o Pagseguro precisa acessar **não** estão protegidas com o middleware auth. Caso estiver o Pagseguro terá como resposta da sua app um erro 403.

**Comment by apsferreira** [comment]
Obrigado meu caro.
