### ISSUE TITLE
Credenciais dinâmicas na notificação

### ISSUE THREAD

**Issue by rodrigopeixotobr** [michaeldouglas/laravel-pagseguro#84]
Olá, estou precisando definir credenciais dinâmicas para as notificações. Tem algum modo de fazer isso?
Para o envio das transações consigo utilizar o método credentials()->create(), mas nas notificações só tem um campo para o credential.

1 - Algum modo de colocar a url de notificação para uma classe minha que monte a variável $credentials e depois repasse para o NotificationController@notification dar continuidade. E depois o callback dá faz o que preciso.

2 - Ou o melhor modo é criar uma função de notificação que consulte manualmente quando o pagseguro enviar o post de notificação? Exemplo:

```
function pagseguroNotificacao(){
    $credentials = PagSeguro::credentials()->create('tokendinamico', 'emaildinamico');
    $transaction = PagSeguro::transaction()->get($_POST['notificationCode'], $credentials);
    $information = $transaction->getInformation();
    ... verifica o status e dá continuidade no pedido ...
}
```

Se a opção 2 for a única opção, seria desde modo a melhor maneira de implementar?

Desde já muito obrigado.

**Comment by isaquesb** [comment]
@rodrigopeixotobr 

A chave do config route.notification.credential onde por padrão esta escrito "default" (para usar a credencial padrão) aceita callable, ou seja, aceita uma função anônima ou ['\Classe', 'método'] que vai resolver a credencial a ser usada.

Esse callable recebe notificationCode e você deve retornar um objeto de credencial para ser usado.

O melhor jeito de implementar varia muito da sua regra de negócio, pois dependendo da sua regra, você vai precisar de informações adicionais para decidir a credencial.

**Comment by rodrigopeixotobr** [comment]
@isaquesb muito obrigado pelo retorno. Já me ajudou bastante, sendo que a credential depende da transação, como posso saber qual é o pedido da notificação apenas com o notificationCode (sem ainda saber qual credential devo utilizar)?

Coloquei desta maneira para chamar a função que vai retornar a credential.

`'credential' => ['App\Libraries\PagSeguro', 'getCredentials']`

E a função assim:

```
public function getCredentials($notificationCode)
{
($pedido = Pedido:find(?) - como saber o $pedido em questão sem os dados da transação?)
$token = $pedido->contrato->token;
$email = $pedido->contrato->email;
$credentials = PagSeguro::credentials()->create($token, $email);
return $credentials;
}
```

Desde já agradeço pela ajuda.

**Comment by isaquesb** [comment]
@rodrigopeixotobr 

O PagSeguro geralmente trabalha com uma credencial apenas e talvez por isso ele não informe nada adicional para que você saiba qual credencial usar.
Porém, para resolver o seu caso, você pode informar URLs de retorno diferentes de acordo com a credencial que você vai usar.
Se você informar ao checkout qual a URL de retorno, ele não vai usar a URL padrão.
Assim você pode informar a URL de retorno como por exemplo: "http://www.seusite.com.br/pagseguro/retorno/c1" para pedidos que devem usar a credencial de código 1.
Dessa forma, quando o pagseguro voltar com as informações, você saberá pela sua URL/Rota que ele esta tratando de um pedido em que foi usado a credencial de código 1 ou X....

Espero que ajude.

**Comment by rodrigopeixotobr** [comment]
@isaquesb genial! Consegui colocar tudo pra funcionar.
Muito obrigado mesmo por toda a ajuda e atenção. 
Parabéns por todo o trabalho.

**Comment by paulocastellano** [comment]
@rodrigopeixotobr 

Pode mandar um exemplo de como você fez?

Eu preciso usar este pacote, porém com credenciais dinamicas em todos os lugares, não somente nas notificações.

Abraços,
