### ISSUE TITLE
Problema na acentuação

### ISSUE THREAD

**Issue by fmcdigital** [michaeldouglas/laravel-pagseguro#85]
Estou com problema ao enviar nome com acento para o pagseguro, segue o erro de xml:

<message>senderName invalid value: Jos?</message>

**Comment by marabesi** [comment]
código que vc está usando pra mandar ?
como vocês tá mandando ????

**Comment by marabesi** [comment]
@fmcdigital vou fechar a issue, caso problema persista é só reabrir : )

**Comment by fmcdigital** [comment]
@marabesi descobri o problema, e não era na acentuação, mas sim numa falha do cadastro em meu ecommerce que permitia o usuário colocar um espaço antes ou depois do nome devido a um erro de digitação.
