### ISSUE TITLE
Sobre capturar dados

### ISSUE THREAD

**Issue by luizmagao** [michaeldouglas/laravel-pagseguro#88]
Bom dia! É possível através de seu plugin capturar dados para saber se aquele objeto foi pago ou não, e colocar dentro da minha aplicação?

**Comment by isaquesb** [comment]
Sim @luizmagao 

Basta seguir os passos do readme em relação a consulta e resgate automático:

Manual
https://github.com/michaeldouglas/laravel-pagseguro#consultando-uma-transa%C3%A7%C3%A3o-manualmente

Automáico
https://github.com/michaeldouglas/laravel-pagseguro#recebendo-notifica%C3%A7%C3%B5es-de-transa%C3%A7%C3%A3o
