### ISSUE TITLE
Checkout trasparente

### ISSUE THREAD

**Issue by lsgoulart** [michaeldouglas/laravel-pagseguro#89]
Procurei aqui nas issues e não encontrei se o Checkout transparente ja foi implementado no package.
Se sim, alguém teria um exemplo de como utilizar?

o/

**Comment by isaquesb** [comment]
@lsgoulart 

Ainda tem temos o recurso de checkout transparente.
Pretendo desenvolver esse e outros recursos nas minhas férias aqui hehe.
