### ISSUE TITLE
Erro de incompatibilidade com Illuminate/support

### ISSUE THREAD

**Issue by paulomartinhago** [michaeldouglas/laravel-pagseguro#9]
Estou tendo problemas na versão 5.0.31 do Laravel, onde ao inserir no composer o require "michael/laravelpagseguro": "dev-master" e dar um composer update, ele me retorna alguns erros junto a esse...

- michael/laravelpagseguro dev-master requires illuminate/support 4.2.* -> satisfiable by illuminate/support[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].

Quando eu retiro do meu composer.json este pacote, e tento dar um composer update, ele não me retorna nenhum erro. Já tentei remover o vendor e o composer lock mas o problema permanece.

Saberia algo a respeito deste problema com o Laravel 5.0.31?

**Comment by michaeldouglas** [comment]
Paulo, agradeço pelo empenho em nós ajudar com esse bug, infelizmente tivemos contra-tempos e não consegui atualizar o projeto. - Porém a partir dessa semana os colaboradores do projeto retornarão a edição do arquivos e também gostaria de ressaltar que sua ajuda é muito bem vinda ao projeto e se quiser tornar-se um colaborador ficarei muito feliz com a sua ajuda :)
