### ISSUE TITLE
Método getAmounts()

### ISSUE THREAD

**Issue by edsonrodsilva** [michaeldouglas/laravel-pagseguro#90]
Oi pessoal.
Eu preciso recuperar o valor que o pagseguro vai me repassar para registrar no banco de dados.
Valor líquido da transação. (propriedade netamount)
Estou usando o metodo getAmounts() mas os valore sempre vem vázios.

`echo "<pre>";
    print_r($information->getAmounts());
echo "</pre>";`

Como posso pegar estes dados?

**Comment by isaquesb** [comment]
@edsonrodsilva ,

Esses valores deveriam sim estar preenchidos.
Inclusive acredito que o getAmounts retorno um objeto com esses valores.

Poderia informar se isso que esta acontecendo contigo é em produção ou sandbox?
Pergunto porque acredite se quiser, os dois ambientes no pagseguro não são idênticos.

**Comment by rafaellupo** [comment]
@edsonrodsilva Também tenho o mesmo problema nos dois ambientes. O Amounts vem sempre com todos valores zerados.

**Comment by edsonrodsilva** [comment]
Ola pessoal,

Eu realmente gostaria de resolver este problema.
Veja o retorno de uma consulta de uma transação manual em sandbox.
usando este código:
-----------------------------------------------------------------------------
$credentials = PagSeguro::credentials()->get();
    $transaction = PagSeguro::transaction()->get('15FC36B5013A44ED85A94DECC1164F38', $credentials);
    $information = $transaction->getInformation();
-----------------------------------------------------------------------------

--------------- problema -------------
Os amounts sempre retorna null, isto acontece também em produção.
#amounts: Amounts {#600 ▼
    #grossAmount: null
    #discountAmount: null
    #feeAmount: null
    #netAmount: null
    #extraAmount: null
  }
--------------- problema -------------


-------------------- return ------------------
Information {#595 ▼
  #code: "15FC36B5-013A-44ED-85A9-4DECC1164F38"
  #date: DateTime {#585 ▼
    +"date": "2017-04-16 08:27:51.000000"
    +"timezone_type": 1
    +"timezone": "-03:00"
  }
  #reference: "278881"
  #type: "1"
  #status: Status {#586 ▼
    #code: "2"
    #name: "Em análise"
  }
  #lastEventDate: DateTime {#598 ▼
    +"date": "2017-04-16 08:33:27.000000"
    +"timezone_type": 1
    +"timezone": "-03:00"
  }
  #paymentMethod: CreditCard {#599 ▼
    #type: "1"
    #typeName: "Cartão de Crédito"
    #names: array:20 [▶]
    #code: "101"
  }
  #amounts: Amounts {#600 ▼
    #grossAmount: null
    #discountAmount: null
    #feeAmount: null
    #netAmount: null
    #extraAmount: null
  }
  #installmentCount: "1"
  #itemCount: "1"
  #items: ItemCollection {#589 ▼
    flag::STD_PROP_LIST: false
    flag::ARRAY_AS_PROPS: false
    iteratorClass: "ArrayIterator"
    storage: array:1 [▼
      0 => Item {#594 ▼
        #id: "1086"
        #description: "KIT WEB -Tabela Lubrificante SEAT - IBIZA - SMART"
        #quantity: "1"
        #amount: "6.00"
        #weight: null
        #shippingCost: null
        #width: null
        #height: null
        #length: null
        #validator: null
      }
    ]
  }
  #sender: Sender {#601 ▼
    #email: "c04927761118410669234@sandbox.pagseguro.com.br"
    #name: "Comprador de Testes"
    #phone: Phone {#596 ▶}
    #documents: DocumentCollection {#588 ▼
      flag::STD_PROP_LIST: false
      flag::ARRAY_AS_PROPS: false
      iteratorClass: "ArrayIterator"
      storage: array:1 [▼
        0 => CPF {#597 ▼
          -number: "68463387136"
          -type: "CPF"
          #validator: null
        }
      ]
    }
    #bornDate: null
    #validator: null
  }
  #shipping: Shipping {#593 ▼
    #address: Address {#587 ▼
      #postalCode: "35740000"
      #street: "PAINEIRA ROSA"
      #number: "300"
      #complement: []
      #district: "FLORESTA ENCANTADA"
      #city: "ESMERALDAS"
      #state: "MG"
      #country: "BRA"
      #validator: null
    }
    #cost: "0.00"
    #type: "3"
    #validator: null
  }
}
-------------------- return ------------------

Alguém tem alguma ideia, eu preciso muito recuperar o valor da compro descontando as taxas do pagseguro.

Valeu.

**Comment by edsonrodsilva** [comment]
Debugando o código descobri que parte do pacote usa a API V2 e V3 do pagseguro,
logo no arquivo de configuracao laravelpagseguro.php.
a linha:  'transactions' => '/v3/transactions', se alteramos para v2 os dados retorna certinho.

Parece que esta faltando adaptar o metodo getInformation() da classe InformationFactory para a V3 da api.

 'url' => [
        'checkout' => '/v2/checkout',
        'transactions' => '/v3/transactions', //Aqui se mudar para v2 retorno certinho
        'transactions-notifications' => '/v3/transactions/notifications',
        'transactions-history' => '/v2/transactions',
        'transactions-abandoned' => '/v2/transactions/abandoned',
    ],

**Comment by rafaellupo** [comment]
@edsonrodsilva Resolvi esse bug. Era uma falha no código mesmo. Vou postar a solução aqui, sugiro que alguém faça um PR (estou a milhão aqui, não dá tempo de mandar uma PR) ou o @michaeldouglas incorpore tão logo quanto puder. 

A versão correta para a url 'transactions' é mesmo a V2. Não está implementado a V3 para os amounts.

Bom vamos lá, o erro está na classe **InformationFactory** método **getAmounts()**.

Código Original:

```php
/**
     * Get Amounts
     * @return Amounts
     */
    public function getAmounts()
    {
        $map = array_fill_keys([
            'grossamount',
            'discountamount',
            'feeamount',
            'netamount',
            'extraamount',
        ], null); 
        $data = array_intersect_key($this->data, $map);
        $normalized = $this->normalizer->amountNormalized($data);
        $amounts = new Amounts($normalized);
        return $amounts;
    }
```

Reparem que a array $map está com seus índices todos em lowercase, mas o retorno do PagSeguro já codificado para Json possuí essas keys em camelCase. Então na busca array_intersect_key, não vai encontrar nada mesmo. A função amountNormalized serve exatamente para transformar em camelCase. Mas deveria ter sido chamada antes. Neste caso, eu reescrevi o método da seguinte forma:

```php
/**
     * Get Amounts
     * @return Amounts
     */
    public function getAmounts()
    {
        $map = array_fill_keys([
            'grossamount',
            'discountamount',
            'feeamount',
            'netamount',
            'extraamount',
        ], null); //Cria um array e preenche com null
        $normalized = $this->normalizer->amountNormalized($map); // Cria um array camelCase cópia de $map
        $data = array_intersect_key($this->data, $normalized); // Busca no retorno do PagSeguro as chaves de $normalized e retorna um array somente com o match.
        $amounts = new Amounts($data); //instancia a Classe Amounts e passa para o construtor o array $data
        return $amounts; // retorna a instância
    }
```

Beleza? Espero ter ajudado com isso!

**Comment by edsonrodsilva** [comment]
Fantástico Rafael, resolveu mesmo, atualizei meu código, tudo certo aqui pra mim.
Vamos aguardar a PR.
Valeu mesmo.

**Comment by isaquesb** [comment]
**Senhores,**

Corrigido na versão 1.0.4 para trabalhar "amounts" com lower e camelCase;
