### ISSUE TITLE
laravelpagseguro.php

### ISSUE THREAD

**Issue by deividfortuna** [michaeldouglas/laravel-pagseguro#91]
Olá,

Eu segui os passos do README para a instalação da lib mas o arquivo laravelpagseguro.php não esta sendo gerado.

Estou usando laravel 5.3.*

Obrigado :see_no_evil:

**Comment by deyvisonrocha** [comment]
@deividfortuna retornar algum erro ao rodar o comando de criação?

**Comment by deividfortuna** [comment]
Não, apenas não cópia o arquivo :disappointed:

**Comment by deividfortuna** [comment]
@deyvisonrocha Não, apenas não cópia o arquivo :disappointed:

**Comment by deyvisonrocha** [comment]
@deividfortuna tu deu um optimize antes de tentar gerar? Podes postar a mensagem que é impressa no terminal após o comando de geração?

**Comment by isaquesb** [comment]
@deividfortuna 

Você esta dizendo que o "publish" não esta copiando o arquivo para a pasta config do laravel certo?
Estranho isso, mas em último caso, copie manualmente mesmo.
Veja se isso acontece também com algum outro pacote.

**Comment by deividfortuna** [comment]
@deyvisonrocha não, apenas segui o README.  Mensagem de retorno:

`Copied Directory [/vendor/laravel/framework/src/Illuminate/Notifications/resources/views] To [/resources/views/vendor/notifications]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]
Publishing complete for tag []!
`

@isaquesb copiei na mão também para a pasta config, mas o method `get` da class `laravel\pagseguro\Config\Config` não me retorna os dados da configuração dentro da pasta vendor e não o da app.

**Comment by Junior-Shyko** [comment]
Eu também estava com esse problema, mais deu um php artisan vendor:publish, que copiou

**Comment by marabesi** [comment]
Issue muito antiga e sem resposta do criado. Se ainda estiver acontecendo por favor abrir uma nova.
