### ISSUE TITLE
with message 'Class 'Input' not found' 

### ISSUE THREAD

**Issue by michelmelo** [michaeldouglas/laravel-pagseguro#92]
olá estou com este problema

exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Input' not found' 
in /home/******/web/******/vendor/michael/laravelpagseguro/src/laravel/pagseguro/Platform/Laravel5.php:24
Stack trace:
#0 {main}

**Comment by deyvisonrocha** [comment]
@michelmelo Você tem que adicionar o LaravelCollective no projeto.

https://laravelcollective.com/docs/5.3/html

**Comment by michelmelo** [comment]
@deyvisonrocha obrigado vou testar com isso

**Comment by isaquesb** [comment]
@michelmelo 

Conseguiu resolver esse problema?
Vocês esta usando mesmo dentro do Laravel? Pois ele é quem resolve o facade "\Input" internamente.
Lembrando que esse controlador é uma proposta de uso no Laravel.

**Comment by michelmelo** [comment]
@isaquesb  vou testa isso daqui a pouco, ja respondo algo.

**Comment by michelmelo** [comment]
fechado @isaquesb ate agora esta resolvido.

**Comment by michelmelo** [comment]
olá ainda continua a dar erro o erro:
estou usando 5.2

**Comment by deyvisonrocha** [comment]
@michelmelo Amigo...

https://laravelcollective.com/docs/5.2/html

**Comment by michelmelo** [comment]
fechado, problema era no laravel que nao estava achando o \imput
reinstalei e foi
