### ISSUE TITLE
Split Payment

### ISSUE THREAD

**Issue by joaopaulopvillela** [michaeldouglas/laravel-pagseguro#94]
Bom dia, 

estou tentando implementar o split payment do pagseguro, mais ainda não tive sucesso, pelo o pouco material que já localizei ele fala que temos que enviar pela a tag **receivers** igual o **item**, e pelo o que verifiquei na biblioteca não esta indo, e class responsável esta indo apenas um e não uma lista e apenas o atributo do **e-mail** e pelo o que verifique os campos são:
```
<primaryReceiver>
    <publicKey>PUBCF30546BDF334CC3A59D772E3636D8D3</publicKey>
</primaryReceiver>
<receivers>
    <receiver>
        <publicKey>PUBCF30546BDF334CC3A59D772E3636D8D4</publicKey>
        <split>
            <amount>20</amount>
            <ratePercent>50</ratePercent>
            <feePercent>50</feePercent>
        </split>
    </receiver>
    <receiver>
        <publicKey>PUBCF30546BDF334CC3A59D772E3636D8D5</publicKey>
        <split>
            <amount>30</amount>
            <ratePercent>50</ratePercent>
            <feePercent>50</feePercent>
        </split>
    </receiver>
</receivers>
```

Desde já muito obrigado.
Para mais detalhes o documento esta em http://download.uol.com.br/pagseguro/docs/pagseguro-transparent-checkout-with-split-payment.pdf

**Comment by isaquesb** [comment]
@joaopaulopvillela 

Realmente essa funcionalidade não esta implementada. Deve ser nova.
Vou verificar a possibilidade de adicionar mais de um receiver de acordo com essa documentação.

**Comment by rbueno** [comment]
Olá @joaopaulopvillela e @marabesi . Vocês conseguiram? Eu irei fazer a mesma coisa para um projeto e gostaria de saber se está funcionando bem.

Obrigado.

**Comment by alexandrekadri** [comment]
Este projeto foi abandonado? Quase 2 anos que postaram essa questão e até agora estão verificando?

**Comment by rbueno** [comment]
Bom dia. 

Não foi abandonado não. Deve haver algo errado com as datas. 

Comecei este ano (2019). Por questão hospitalar tive que interromper. Voltei agora. 

Rafael

**Comment by michaeldouglas** [comment]
@alexandrekadri vou dar uma olhada e ver se consigo fazer essa questão. Já estou com a documentação e mãos: https://dev.pagseguro.uol.com.br/docs/split-de-pagamento

**Comment by fabiomdsdj** [comment]
Olá, também estou a implementar em meu projeto, alguma posição a respeito?
