### ISSUE TITLE
Erro ao usar em sandbox

### ISSUE THREAD

**Issue by yakkobr** [michaeldouglas/laravel-pagseguro#95]
ao usar o componente em modo sandbox quando eu verifico uma transação usando:

$transaction = PagSeguro::transaction()->get("codigo", $credentials);

obtenho o seguinte erro:
Error on getStatus: 401-Unauthorized

fui debugar um pouco (não mando muito bem), mas cheguei no arquivo: Transaction.php, a variavel $url esta recebendo:

https://ws.pagseguro.uol.com.br/v3/transactions/

não deveria ser:

https://ws.sandbox.pagseguro.uol.com.br/v3/transactions/

um grande abraço e muito obrigado pelo componente.

**Comment by isaquesb** [comment]
@yakkobr 

Tem certeza que alterou o arquivo de config correto?
Pois tem o arquivo do pacote e tem o arquivo que é publicado na pasta de configs do laravel (laravelpagseguro.php).
A chave para usar sandbox é "use-sandbox" que deve ser alterada para true.

**Comment by yakkobr** [comment]
Hum... boa vou verificar isso, pois eu estou usando via programação e não na pagina de configuração... pra ficar mais facil ;)

**Comment by yakkobr** [comment]
realmente neste caso era esta opção, vlw.
