### ISSUE TITLE
Codigo da Transação

### ISSUE THREAD

**Issue by yakkobr** [michaeldouglas/laravel-pagseguro#96]
Na documentação eu não achei como localizar o codigo da transação, como eu faria isso?
um grande abraço.

**Comment by isaquesb** [comment]
@yakkobr 

O código da transação esta presente no objeto "Information" que é dado à você após o envio para o pagseguro conforme os exemplos.
Nos exemplos tem por exemplo: "$information->getCode()" que é o código da transação.

**Comment by yakkobr** [comment]
Então @isaquesb , esse codigo que é retornado é o da notificação daquele momento, por este codigo não consigo realizar a pesquisa... existem 2 ou mais codigos:
1 - transação/notificação do instante
2 - transação geral
3 ou X - cada vez que é feito uma notificação do pagseguro para o cliente

o codigo que é utilizado para fazer consultas é o da transação geral e não o codigo da notificação que estou pegando pelo getCode().

quando eu faço consulta usando o getCode() ele me retorna um erro 400.

erro:
Error on getStatus: 400-<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>13003</code><message>invalid transactionCode value: 21C580541FB61FB6F16774932F8CB1EE871F</message></error></errors>

agora se eu fizer a consulta usando o codigo da transação geral:
Código da transação: 62E5CFDBDAF24509B8479728F3F1A3F9

eu obtenho acesso as informações da transação, como o status: < Em análise

**Comment by yakkobr** [comment]
O codigo que usei foi este:

public function status(Request $request){
        header("access-control-allow-origin: https://sandbox.pagseguro.uol.com.br");
        $notificacao = $_POST["notificationType"];
        $codigo = $_POST["notificationCode"];

        Config::set('laravelpagseguro.use-sandbox', true);
        $credentials = PagSeguro::credentials()->create("minha_chave", "meu_email");
        try{
            $transaction = PagSeguro::transaction()->get($codigo, $credentials); 
            $information = $transaction->getInformation();

            return $information->getStatus()->getName();
        }
        catch (\Exception $ex){
            return "Erro: " . $ex->getMessage();
        }
    }

**Comment by isaquesb** [comment]
@yakkobr 

Existem 2 códigos: O de Notificação e o de Transação.

O de notificação é usado para voltar até o pagseguro e buscar as informações referente há algo (geralmente transações).
O de transação é para realizar procedimentos relacionados à transações, onde o mais comum é verificar o status por exemplo.

Ao receber o código de notificação, a lib vai até o pagseguro verificar do que se trata (se você configurou o retorno automático: https://github.com/michaeldouglas/laravel-pagseguro#recebendo-notifica%C3%A7%C3%B5es-de-transa%C3%A7%C3%A3o).
O pagseguro informa que a notificação é referente à uma transação, e passa as informações da mesma.

A lib identifica que são dados de uma transação, e popula um objeto "Information" com esses dados.
Depois disso ela te disponibiliza esse objeto, onde o "getCode()" te dá o código da transação.

Ambos tem o "getCode()", tanto o objeto de Notificação, quanto o "Information" que é retornado no "check()", onde você tem acesso ao código da transação.

Na proposta de "controller" da lib você encontra esse exemplo de dinâmica que acabei de falar:
https://github.com/michaeldouglas/laravel-pagseguro/blob/master/src/laravel/pagseguro/Platform/Laravel5/NotificationController.php

Ele recebe o código de notificação, faz o check (volta no pagseguro), e depois cria um objeto do tipo de informação referente à essa notificação, que na maioria das vezes é transação. Portanto o maioria das vezes que você chamar Notification::check(), ele te dará um Transaction\Information.

Resumindo, você NÃO pode informar como código de transação, um código de notificação.
Se você já tem o código de transação que vai trabalhar, pode seguir esse exemplo que você postou para consultar as informações que desejar. Se você tem um código de NOTIFICAÇÃO, precisa fazer o check() para pegar as informações da transação, igual o código que esta no controller do link acima.

Não sei se fui pouco claro. Mas diz aí se entendeu blz? Vlw.

**Comment by yakkobr** [comment]
@isaquesb, ok vc foi claro, mas ai que esta o problema, como que eu faço esse bendito callback da notificação de transação? eu acho que estou pecando ai, pois não fiz justo essa parte pq não consegui, se tiver algum artigo para me indicar serei imensamente grato.
Obrigado.

**Comment by yakkobr** [comment]
@isaquesb, olhando um pouco mais vamos ver se entendi, eu tenho que criar 2 itens:

1º) nas rotas:
Route::post('/pagseguro/notification', [
    'uses' => '\laravel\pagseguro\Platform\Laravel5\NotificationController@notification',
    'as' => 'pagseguro.notification',
]);

**E**

2º) no config laravelpagseguro.php:
'routes' => [
    'notification' => [
        'callback' => ['MyNotificationClass', 'myMethod'], // Callable
        'credential' => 'default',
        'route-name' => 'pagseguro.notification', // Nome da rota
    ],
],

desta forma irei conseguir obter o codigo da transação, correto?

**Comment by isaquesb** [comment]
@yakkobr 

Isso,
Certifique-se de não colocar essa rota com middleware de csrf, auth ou qualquer outro do tipo.
Ao receber o POST do PagSeguro, ele vai te dar um objeto Information de Transação na sua classe MyNotificationClass::myMethod($info).
Aí ao chamar o $info->getCode() você terá o código da transação da qual essa notificação se trata.
Se MyNotificationClass tiver namespace, favor colocar com o namespace dela.
['\MyNamespace\To\Notification\MyNotificationClass', 'myMethod'].

**Comment by yakkobr** [comment]
@isaquesb , muito muito muito obrigado.

**Comment by tulio271** [comment]
@isaquesb  eu conseguiria fazer essa consulta de forma manual ? sem receber retorno do pagseguro minha aplicação mesmo ir lá e fazer a consulta

**Comment by isaquesb** [comment]
@tulio271 .
Sim.
https://github.com/michaeldouglas/laravel-pagseguro#consultando-uma-transa%C3%A7%C3%A3o-manualmente

**Comment by tulio271** [comment]
@isaquesb  então irmão tentei fazer isso mas não deu certo, criei o pagamento, me gera um código, mas não da para consultar por ele, até criei um tópico no stack se puder me ajudar : https://pt.stackoverflow.com/questions/415762/consulta-transa%c3%a7%c3%a3o-manualmente-laravel-pagseguro/415845#415845
