### ISSUE TITLE
Código de Notificação

### ISSUE THREAD

**Issue by fmcdigital** [michaeldouglas/laravel-pagseguro#97]
Olá,
Estou tentando entender a notificação do PagSeguro, já configurei a rota POST e coloquei a mesma no config do módulo, porém no painel do PagSeguro eu coloco a mesma url desta rota para o retorno, ou seria uma outra?

Obrigado.

**Comment by yakkobr** [comment]
@fmcdigital, dá uma olhada no meu topico, é a uma duvida parecida com a tua.... https://github.com/michaeldouglas/laravel-pagseguro/issues/96

**Comment by isaquesb** [comment]
@fmcdigital 

Se você fez o checkout por essa biblioteca, ele geralmente já informa ao PagSeguro qual é a URL de retorno, pois a lib já lê a sua configuração e pega (ou monta) a URL. Portanto não seria necessário colocar URL de retorno no PagSeguro, pois a transação já diz qual é.

Outra coisa, você não pode confundir a URL de redirect com a de retorno (só para reforçar).
Redirect é pra onde o usuário vai depois de realizar o pagamento.
Retorno é para onde o pagseguro envia as notificações quando sua transação muda de status.

Além disso, a lib também pega a URL de redirect do config automaticamente se você não especificar uma quando vai enviar o checkout.

**Comment by fmcdigital** [comment]
@isaquesb sim, eu já consegui fazer funcionar aqui, a url de notificação estava com cache e agora deu certo.

Mas, uma outra dúvida que surgiu foi ao utilizar um controller como Callback me retornava o erro http 500, no qual o método "notify" da class NotificationController não encontrava minha class que estava dentro da pasta Controllers, aí tive que modificar a função notify para atualizar o status do pedido.

**Comment by rafaellupo** [comment]
@fmcdigital  se a sua função de callback não for um Callable, ou seja, um método estático, ele vai dar erro. Fora isso, vejo a possibilidade do caminho da classe estar errado. No meu caso, como eu atualizo também o status do pedido, implementei dentro de um model mesmo através de uma trait para organizar legal. Lembrando que se houverem "helper methods" dentro da classe que seja necessário chamar também pelo callable, eles precisam ser estáticos, para chamar como `self::metodo()` a não ser que façam parte de uma nova instância.

**Comment by marabesi** [comment]
Issue resolvida.
