### ISSUE TITLE
 'Callback is a not valid PHP callback' 

### ISSUE THREAD

**Issue by michelmelo** [michaeldouglas/laravel-pagseguro#99]
ola posso esta fazendo algo de errado mas nao sei o que esta mal.
o meu route esta assim:
`'routes' => [
        'redirect' => [
            'route-name' => 'pagseguro.redirect', // Criar uma rota com este nome
        ],
        'notification' => [
            'callback' => ['\app\Http\Controllers\PagamentoController','update'],
            //null, // Callable callback to Notification function (notificationInfo) : void {}
            'credential' => 'default', // Callable resolve credential function (notificationCode) : Credentials {}
            'route-name' => 'pagseguro.notification', // Criar uma rota com este nome
        ],
    ],`

e estou tento o erro:
exception 'RuntimeException' with message 'Callback is a not valid PHP callback' 

algo de errado no callback?

**Comment by isaquesb** [comment]
Esse problema já foi explicado aqui: #81
